import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "decoration/casino",
  size: 32,
  width: 32,
  height: 48,
  pixels: [
    "................................",
    "................................",
    "................................",
    "................................",
    "...............ii...............",
    "...............ii...............",
    "...............PP...............",
    "..............yyyy..............",
    ".............UUUUUU.............",
    "............iiiiiiii............",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUssssssssssssiSSSSk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......SPssssssssssssPSSSSk.....",
    ".......SUoosyysoosyysiSdSdk.....",
    ".......Sooooooooooooooooook.....",
    ".......Syyyyyyyyyyyyyyyyyyk.....",
    "................................",
    "................................",
  ],
};

export default recipe;
