import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "decoration/ring-post",
  size: 16,
  width: 16,
  height: 32,
  pixels: [
    "................",
    "......xRRx......",
    ".....xRRRRx.....",
    ".....RRRRRR.....",
    ".....RRRRRR.....",
    ".....xRRRRx.....",
    "......xRRx......",
    "......dDDd......",
    "......dwwd......",
    "......dDDd......",
    "......hDDh......",
    "......dDDd......",
    "......dwwd......",
    "......dDDd......",
    "......hDDh......",
    "......dDDd......",
    "......dDDd......",
    "......dwwd......",
    "......dDDd......",
    "......hDDh......",
    "......dDDd......",
    "......dDDd......",
    "......dDDd......",
    "......hDDh......",
    "......dDDd......",
    "......dDDd......",
    ".....dDDDDd.....",
    ".....kDDDDk.....",
    "....kQQQQQQk....",
    "....kQQQQQQk....",
    "....kkkkkkkk....",
    "................",
  ],
};

export default recipe;
