import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "decoration/roulette",
  size: 32,
  width: 32,
  height: 32,
  pixels: [
    "................................",
    "................................",
    "...........kkkkkkkkkk...........",
    ".......kkkdddddddddddkkk........",
    ".....kkddDDDDDDDDDDDDDDddkk.....",
    "....kddDDkRkRkRkRkRkRkRDDdk.....",
    "...kdDDkRxkkRkkRkkRkkRxkDDdk....",
    "..kdDDRxqqqqqqqqqqqqqqxRkDDdk...",
    "..kdDkqqqGGGGGGGGGGGGqqkRDDdk...",
    ".kdDRqqGGgggggggggggGGqqxkDDdk..",
    ".kdDkqGGgggoooooogggggGGqRDDdk..",
    ".kdDRqGgggooooooooogggGqqkDDdk..",
    ".kdDkqGgggoooyyooooogggGqRDDdk..",
    ".kdDRqGgggooyooyoooogggGqkDDdk..",
    ".kdDkqGgggooyooyoooogggGqRDDdk..",
    ".kdDRqGgggoooyyooooogggGqkDDdk..",
    ".kdDkqGgggooooooooogggGGqRDDdk..",
    ".kdDRqqGgggoooooogggggGqqkDDdk..",
    "..kdDkqqGGgggggggggggGGqqRDDdk..",
    "..kdDRxqqGGGGGGGGGGGGqqxkDDdk...",
    "..kdDDkRqqqqqqqqqqqqqqRkDDDdk...",
    "...kdDDRxkkRkkRkkRkkRxkDDDdk....",
    "....kddDDkRkRkRkRkRkRkDDddk.....",
    ".....kkddDDDDDDDDDDDDDDdkk......",
    ".......kkkdddddddddddkkk........",
    "...........kkkkkkkkkk...........",
    "...........lGGGGGGGGl...........",
    "..........lGggggggggGl..........",
    "..........lGggggggggGl..........",
    "...........lGGGGGGGGl...........",
    "............kllllllk............",
    "................................",
  ],
};

export default recipe;
