import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "decoration/slot-machine",
  size: 16,
  width: 16,
  height: 32,
  pixels: [
    "................",
    "................",
    "................",
    "....kkkkkk......",
    "...koooooook....",
    "...koyyyyyok....",
    "...koyiyiyok....",
    "...kooooooook...",
    "..ksSSSSSSSsk...",
    "..kSssssssSSk...",
    "..kSskkkkksSk...",
    "..kSskoyoksSkk..",
    "..kSskyiyksSkrk.",
    "..kSskoyoksSkrk.",
    "..kSskkkkksSkok.",
    "..kSssssssSSkk..",
    "..kSsSSSSSsSSk..",
    "..kSskooooksSk..",
    "..kSskoSSoksSk..",
    "..kSskoSSoksSk..",
    "..kSskooooksSk..",
    "..kSssssssSSSk..",
    "..kSSSSSSSSSSk..",
    "..kSswwwwssSSk..",
    "..kSswooowssSk..",
    "..kSswooowssSk..",
    "..kSswwwwssSSk..",
    "..kSSSSSSSSSSk..",
    "..kkkkkkkkkkkk..",
    "..kQQQQQQQQQQk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
};

export default recipe;
