import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "structure/big-tree",
  size: 48,
  width: 48,
  height: 64,
  pixels: [
    "................................................", 
    "....................kkkkk.......................", 
    "................kkkkkGGGGGkkk...................", 
    ".............kkkGGGGGGGGGGGGGkk.................", 
    "...........kkGGGGgGGGGGGGGGGGGGkk...............", 
    ".........kkGGGggGGGGGGGGGGGGGGGGGkk.............", 
    "........kGGGgggGGGGGGGGGlGGGGGGGGGGk............", 
    ".......kGGGgggGGGGGGGGGGGlGGGGGGGGGGkk..........", 
    "......kGGGGggGGGGGGGGGGGGGGGGGGGGGGGGGk.........", 
    ".....kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk........", 
    "....kGGGGGGGGGGGlGGGGGGGGGGGGGGGGGGGGGGGk.......", 
    "...kGGGGGGGGGGGGlGGGGGGGGGGGGGGGGGGGGGGGGk......", 
    "...kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk......", 
    "..kGGGggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk.....", 
    "..kGGgggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk.....", 
    "..kGGgggGGGGGGGGGGGGGlGGGGGGGGGGGGGGGGGGGGk.....", 
    ".kGGGGGGGGGGGGGGGGGGGGlGGGGGGGGGGGGGGGGGGGGk....", 
    ".kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk....", 
    ".kGGGGGGGGlGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk....", 
    ".kGGGGGGGGlGGGGGGGGGGGGGGGGGGGGGGGGggGGGGGGk....", 
    ".kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgggGGGGGGk....", 
    "..kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgggGGGGGk.....", 
    "..kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk.....", 
    "...kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk......", 
    "...kkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkk......", 
    "....kkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkk.......", 
    ".....kktGGGGGGGGGGGGGGGGGGGGGGGGGGGGtkk.........", 
    "......kktGGGGGGttGGGGGGGGGGGttGGGGtkk...........", 
    ".......kkttGGGGttGGGGGGGGGGGttGGttkk............", 
    ".........kkttGGttGGGGmMGGGGttttkk...............", 
    "...........kkttttGGGGmMGGGttkk..................", 
    "..............kkkttGGmMGttkkk...................", 
    "..................kkkmMkkk......................", 
    ".....................mMD........................", 
    "....................dmMD........................", 
    "....................dmMDd.......................", 
    "...................DdmMDd.......................", 
    "...................DdmMMd.......................", 
    "...................DdmMMd.......................", 
    "..................DddmMMdd......................", 
    "..................DddmMMdd......................", 
    "..................DddmMMdd......................", 
    ".................DdddmMMddd.....................", 
    ".................DdddmMMddd.....................", 
    ".................DddmmMMMddd....................", 
    "................DdddmmMMMddd....................", 
    "................DddmmMMMMddd....................", 
    "...............DdddmmMMMMdddd...................", 
    "...............DddmmMMMMMdddd...................", 
    "..............DdddmmMMMMMdddd...................", 
    "..............DddmmMMMMMMdddd...................", 
    ".............DdddmmMMMMMMddddd..................", 
    ".............DddmmMMMMMMMddddd..................", 
    "............DdddmmMMMMMMMdddddd.................", 
    "...........DddmmMMMMMMMMMddddddd................", 
    "..........DdddmmMMMMMMMMMddddddd................", 
    ".........DddmmmMMMMMMMMMMMdddddddd..............", 
    "........DddmmmMMMMMMMMMMMMMddddddd..............", 
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkk..............", 
    "......kGGGGGGGGGGGGGGGGGGGGGGGGGGGk.............", 
    ".....kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk............", 
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........", 
    "................................................", 
    "................................................", 
  ],
};

export default recipe;
