import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe =
  {
    name: "structure/carpenter-workshop",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "................................",
      ".............ll.................",
      "............lLLl................",
      "...........lLLLLl...............",
      "..........lLGGGGLl..............",
      ".........lLGGGGGGLl.............",
      "........lLGGGGGGGGLl............",
      ".......lLGGGGGGGGGGLl...........",
      "......lLGGGGGGGGGGGGLl..........",
      ".....lLGGGGGGGGGGGGGGLl.........",
      "....lLGGgGGgGGgGGgGGgGLl........",
      "...lLGGGGGGGGGGGGGGGGGGLl.......",
      "..lLGGGGGGGGGGGGGGGGGGGGLl......",
      ".lLGGGGGGGGGGGGGGGGGGGGGGLl.....",
      "lLLLLLLLLLLLLLLLLLLLLLLLLLLl....",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMM....",
      "MWWWWWWWWWWWWWWWWWWWWWWWWWWM....",
      "MWMWWWWWWWWWWWWWWWWWWWWWWMWM....",
      "MWMW..mmmm.WWWWWWWW.mmmm.WMW....",
      "MWMW.mWWWWm.WWWWWW.mWWWWm.WM....",
      "MWMW.mWqqWm.WWWWWW.mWqqWm.WM....",
      "MWMW.mWqqWm.WWWWWW.mWqqWm.WM....",
      "MWMW.mWWWWm.WWWWWW.mWWWWm.WM....",
      "MWMW..mmmm.WWWWWWWW.mmmm.WMW....",
      "MWMWWWWWWWWWWWWWWWWWWWWWWMWM....",
      "MWMWWWWWWWkkkkkkkkWWWWWWWMWM....",
      "MWMWWWWWWWkddddddkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MMMMMMMMMMkdDDDDdkMMMMMMMMM.....",
      "kMMMMMMMMMkkkkkkkkMMMMMMMMk.....",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  }
;

export default recipe;
