import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/cottage-opportunist",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............kk...............",
      "..............Uukk..............",
      ".............Uuuukk.............",
      "............Uuuuuukk............",
      "............Uukuukkk............",
      "...........Uuuuuuuukk...........",
      "..........Uuuuuuuuuukk..........",
      ".........Uuukuukuukuukk.........",
      "........Uuuuuuukkuuuuukk........",
      ".......Uuuuuuukqqkuuuuukk.......",
      ".......Ukuukuukqnkuukuukk.......",
      "......Uuuuuuuukqqkuuuuuukk......",
      ".....Uuuuuuuuuukkuuuuuuuukk.....",
      "....Uukuukuukuukuukuukuukukk....",
      "...Uuuuuuuuuuuuuuuuuuuuuuuukk...",
      "..Uuuuuuuuuuuuuuuuuuuuuuuuuukk..",
      "..Uuukuukuukuukuukuukuukuukukk..",
      ".Uuuuuuuuuuuuuuuuuuuuuuuuuuuukk.",
      "Uuuuuuuuuuuuuuuuuuuuuuuuuuuuuukk",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
