import { type PixelRecipe } from "../../types";

// Cozy timber cottage. Shingled gable roof (per-personality hue) with a leaded
// gable window; NW sun so the roof's left edge and the wall's left face are lit
// while the SE side falls to woodDark/bark. Reflective leaded windows and a warm
// lamplit door make it lived-in. Generated to keep all five variants in lockstep.
const recipe: PixelRecipe = {
    name: "structure/cottage-opportunist",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............UN...............",
      "..............UuNN..............",
      ".............UNNNNN.............",
      "............UuuuuuNN............",
      "............UuuuuuNN............",
      "...........UuuuuuuuNN...........",
      "..........UNNNNNNNNNNN..........",
      ".........UuuuuuuuuuuuNN.........",
      "........UuuuuuukkuuuuuNN........",
      ".......UuuuuuukqqkuuuuuNN.......",
      ".......UNNNNNNkqnkNNNNNNN.......",
      "......UuuuuuuukqqkuuuuuuNN......",
      ".....UuuuuuuuuukkuuuuuuuuNN.....",
      "....UuuuuuuuuuuuuuuuuuuuuuNN....",
      "...UNNNNNNNNNNNNNNNNNNNNNNNNN...",
      "..UuuuuuuuuuuuuuuuuuuuuuuuuuNN..",
      "..UuuuuuuuuuuuuuuuuuuuuuuuuuNN..",
      ".UuuuuuuuuuuuuuuuuuuuuuuuuuuuNN.",
      "UNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
      "..MMMMMMMMMMMMMMMMMMMMMMMMMMMM..",
      "..MhmmmmmmmmmmmmmmmmmmmmmmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhDDDDDDDDDDDDDDDDMMMMMMMMHM..",
      "..MhdddMMMMMddddddddMMMMMmmmHM..",
      "..MhdddMqqSMddddddddMqqSMmmmHM..",
      "..MhdddMqSSMddddddddMqSSMmmmHM..",
      "..MhdddMSSVMddddddddMSSVMmmmHM..",
      "..MhdddMMMMMddddddddMMMMMmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhDDDDDDDDDDDDDDDDMMMMMMMMHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhddddddddddddddddmmmmmmmmHM..",
      "..MhDDDDDDDDDDDDDDDDMMMMMMMMHM..",
      "..MhdddddddddMMMMMMdmmmmmmmmHM..",
      "..MhdddddddddMyyooMdmmmmmmmmHM..",
      "..MhdddddddddMooooMdmmmmmmmmHM..",
      "..MhdddddddddMddddMdmmmmmmmmHM..",
      "..MhdddddddddMddodMdmmmmmmmmHM..",
      "..MhdddddddddMddddMdmmmmmmmmHM..",
      "..MhdddddddddMddddMdmmmmmmmmHM..",
      "..MhdddddddddMddddMdmmmmmmmmHM..",
      "..MMMMMMMMMMMMMMMMMMMMMMMMMMMM..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWbbbbbbbbbbbbbbb.",
      "..MMMMMMMMMMMMMMMMMMMMMMMMMMMM..",
    ],
};

export default recipe;
