import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/home",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............HH...............",
      "..............WhHH..............",
      ".............WwwwHH.............",
      "............WwwwwwHH............",
      "............WwhwwHHH............",
      "...........WwwwwwwwHH...........",
      "..........WwwwwwwwwwHH..........",
      ".........WwwhwwhwwhwwHH.........",
      "........WwwwwwwkkwwwwwHH........",
      ".......WwwwwwwkqqkwwwwwHH.......",
      ".......WhwwhwwkqnkwwhwwHH.......",
      "......WwwwwwwwkqqkwwwwwwHH......",
      ".....WwwwwwwwwwkkwwwwwwwwHH.....",
      "....WwhwwhwwhwwhwwhwwhwwhwHH....",
      "...WwwwwwwwwwwwwwwwwwwwwwwwHH...",
      "..WwwwwwwwwwwwwwwwwwwwwwwwwwHH..",
      "..WwwhwwhwwhwwhwwhwwhwwhwwhwHH..",
      ".WwwwwwwwwwwwwwwwwwwwwwwwwwwwHH.",
      "WwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHH",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
