import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/weather-station",
    size: 32,
    width: 48,
    height: 48,
    pixels: [
      "................................................",
      "................................................",
      "....................ssssssss....................",
      "...................ssSSSSSSNN...................",
      ".................ssSSSSSSSSSSNN.................",
      "................ssSSSSSSSSSSSSNN................",
      "...............ssSSSSSSSSSSSSSSNN...............",
      ".............ssSSSSSSSSSSSSSSSSSSNN.............",
      "............ssSSSSSSSSSSSSSSSSSSSSNN............",
      "...........ssSSSSSSSSSSSSSSSSSSSSSSNN...........",
      ".........ssSSSSSSSSSSSSSSSSSSSSSSSSSSNN.........",
      "........ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN........",
      ".......ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.......",
      ".....ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.....",
      "....ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN....",
      "...ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN...",
      ".ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.",
      "ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "...qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQkkkkkkQQQQQQQQQQQQQQQQQQkkkkkkQQQQNN...",
      "...qqQQQQkooookQQQQQQQQQQQQQQQQQQkooookQQQQNN...",
      "...qqQQQQkoyyokQQQQQQQQQQQQQQQQQQkoyyokQQQQNN...",
      "...qqQQQQkoyyokQQQQQQQQQQQQQQQQQQkoyyokQQQQNN...",
      "...qqQQQQkooookQQQQQQQQQQQQQQQQQQkooookQQQQNN...",
      "...qqQQQQkkkkkkQQQQQQQQQQQQQQQQQQkkkkkkQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkkkkkkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...",
    ],
};

export default recipe;
