import { type PixelRecipe } from "./types";

export const BASE_RECIPES: PixelRecipe[] = [
  {
    // Shore — a foam + wet-sand band along the TOP edge of the tile. Placed on a
    // LAND tile that borders ocean and rotated (0/90/180/270) so the band faces
    // the adjacent water. Transparent elsewhere so the land tile shows through.
    // w=white foam, e=ocean highlight, T/W=wet sand.
    name: "tile/shore",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wewwewwwewwwewww",
      "TTwTTTwTTTTwTTTT",
      "TTTTTTTTTTTTTTTT",
      "WTTWTTTTWTTTWTTT",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Island wall / cliff — a raised stone retaining wall along the TOP edge of
    // the tile, sitting on the LAND margin where it meets the ocean. Authored
    // top-edge-up like `tile/shore` and rotated (0/90/180/270) so the wall face
    // looks out over the adjacent water; transparent below so the land tile
    // shows through. q=stone light (cap), Q=stone dark (face), k=near-black
    // (shadow seam at the base of the cliff).
    name: "tile/wall",
    size: 16,
    pixels: [
      "qqqqqqqqqqqqqqqq",
      "qqqqqqqqqqqqqqqq",
      "QqQQqQQqQQqQQqQq",
      "QQQQQQQQQQQQQQQQ",
      "QQkQQQkQQQkQQQkQ",
      "QQQQQQQQQQQQQQQQ",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Wooden island wall — a plank retaining wall along the TOP edge of the
    // tile, used on the carpentry island margin so its shoreline reads as a
    // built wooden bulwark. Authored top-edge-up like `tile/wall`, rotated to
    // face the water. D=wood dark (posts/seam), d=wood light (planks),
    // k=near-black (shadow seam at the waterline).
    name: "tile/wall-wood",
    size: 16,
    pixels: [
      "dddddddddddddddd",
      "dddDddddDddddDdd",
      "dddDddddDddddDdd",
      "DDDDDDDDDDDDDDDD",
      "dddddddddddddddd",
      "dddDddddDddddDdd",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Sandy beach edge — a fuller wet-sand + foam band along the TOP edge, used
    // on farm-field island margins so they read as a soft sandy shore rather
    // than a hard wall. Authored top-edge-up like `tile/shore`, rotated to face
    // the water. w=foam, T=sand, W=tan/wet sand, e=ocean highlight.
    name: "tile/shore-sand",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wewwwewwwewwweww",
      "TTTTTTTTTTTTTTTT",
      "TTWTTTWTTTWTTTWT",
      "TTTTTTTTTTTTTTTT",
      "WTTTWTTTWTTTWTTT",
      "TTTTTTTTTTTTTTTT",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Ocean — fills the gaps between/around the playable regions so the world
    // reads as islands in an ocean. Drawn under everything (it's non-walkable).
    // Gentle wave flecks (e) over two blues (v deeper between, V base) give the
    // water some life without animating. (Animated foam is a separate dynamic
    // overlay — see tile/foam-a/b/c.)
    name: "tile/ocean",
    size: 16,
    pixels: [
      "VVVVVVVVVVVVVVVV",
      "VVVVeVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVeVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVVVVeV",
      "VVVVVVVVVVVVVVVV",
      "eVVVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVeVVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVeVVVV",
      "VVeVVVVVVVVVVVVV",
      "VVVVVVVVVeVVVVVV",
      "VVVVeVVVVVVVVeVV",
      "VVVVVVVVVVVVVVVV",
    ],
  },
  {
    // Animated foam overlay, frame A. Drawn over ocean tiles by the main-thread
    // render loop, cycling A→B→C for a gentle shimmer. Transparent base (.) so
    // the static ocean shows through; e=highlight, w=white foam crest.
    name: "tile/foam-a",
    size: 16,
    pixels: [
      "................",
      "..e.........e...",
      "................",
      ".......w........",
      "................",
      "............e...",
      "...e............",
      "................",
      ".........w......",
      "................",
      "..e.........e...",
      "................",
      "......w.........",
      "................",
      ".............e..",
      "................",
    ],
  },
  {
    name: "tile/foam-b",
    size: 16,
    pixels: [
      "................",
      ".....e.......e..",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".............e..",
      "......w.........",
      "................",
      "...e............",
      "................",
      ".........e......",
      "....w...........",
      "................",
      "..e.......e.....",
      "................",
    ],
  },
  {
    name: "tile/foam-c",
    size: 16,
    pixels: [
      "................",
      "........e.....e.",
      "...w............",
      "................",
      "..........e.....",
      ".....e..........",
      "................",
      "............w...",
      "..e.............",
      "................",
      ".......e........",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".........e......",
    ],
  },
  {
    name: "tile/grass",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },
  // ── brief 45 — seasonal grass variants ────────────────────────────────────────
  // Render-only ground-tile treatments selected per-season in backdropFrame.
  // Spring = the freshest base grass + light flecks; summer = deeper/drier base;
  // autumn = golden/orange flecks over a tan-dried base; winter = snow-dusted.
  // Each shares the base grass layout so they read as the SAME field changing
  // through the year. All swatch chars are EDG32 (see SWATCH).
  {
    name: "tile/grass-spring",
    size: 16,
    pixels: [
      "ccCgccccccccgccc",
      "cCcccCccccGcccGc",
      "cccgcccccccCGccc",
      "cGcccccGcccccgcc",
      "ccCccccccGcccCcc",
      "ccGccccgccccccCc",
      "ccccCcccCGccccGc",
      "cgccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccgcccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccgcccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccgcccCccccccccc",
    ],
  },
  {
    // Summer: deeper, drier — base swapped to the darker grass-base (c only),
    // sparse light highlights, the odd dry wheat-tan fleck (b).
    name: "tile/grass-summer",
    size: 16,
    pixels: [
      "cccccccccccccccc",
      "ccccGccccccccccc",
      "cccccccccbccGccc",
      "cGcccccccccccccc",
      "cccccccccGcccccc",
      "ccGcccccccccccbc",
      "ccccGcccGcccccGc",
      "cccccccccccccccc",
      "cGcccccGcccGcccc",
      "ccccbccccccccccc",
      "cccccccccGcccccc",
      "ccccccGccccccccc",
      "cGccccccccccccbc",
      "cccccccGccccGccc",
      "cccGccccccGccccc",
      "ccccccGccccccccc",
    ],
  },
  {
    // Autumn: golden/orange flecks (a/A) + tan (b) over the base grass — the
    // field turning. A few green specks linger so it's clearly the same grass.
    name: "tile/grass-autumn",
    size: 16,
    pixels: [
      "ccAcccccccacccbc",
      "ccccaccccAcccacc",
      "cbccccccccccAccc",
      "cAcccccacccccbcc",
      "ccacccccccccAccc",
      "ccAccccbcccccccc",
      "ccccacccaAcccccA",
      "cbccccccccccaccc",
      "cAcccccacccaAccc",
      "ccccbccccccccAca",
      "ccacccccccAccccc",
      "ccccccAcccbcccac",
      "cacccAcccccccccc",
      "ccccccAcccccaccc",
      "cccacccccacacccc",
      "ccbcccacccccccac",
    ],
  },
  {
    // Winter: snow-dusted — a near-solid snow (n) blanket with frozen-grass (c)
    // patches showing through and faint blue-grey shadow (Q) at clumps.
    name: "tile/grass-winter",
    size: 16,
    pixels: [
      "nnnnnnnnnnnnnnnn",
      "nnnnQnnnnnnnnQnn",
      "nncnnnnnnnnnnnnn",
      "nnnnnnnnQnnnnnnn",
      "nnQnnnnnnnnncnnn",
      "nnnnnnnnnnnnnnnn",
      "nnnnnncnnnQnnnnn",
      "nQnnnnnnnnnnnnnn",
      "nnnnnnnQnnnnncnn",
      "nnncnnnnnnnnnnnn",
      "nnnnnnnnQnnnnnQn",
      "nnQnnnnnnnnnnnnn",
      "nnnnncnnnnnQnnnn",
      "nnnnnnnnnnnnnnnn",
      "nQnnnnnnQnnncnnn",
      "nnnnnnnnnnnnnnnn",
    ],
  },
  {
    name: "tile/path",
    size: 16,
    pixels: [
      "TTTTTTTTTTTTTTTT",
      "TWTTWTTTWTTTWTTT",
      "TTTTTTTWTTTTTTTT",
      "TWTTTTTTTTTTTTWT",
      "TTTTTTTTTTWTTTTT",
      "TTWTTTTWTTTTTTTT",
      "TTTTTWTTTTTTWTTT",
      "TTTTTTTTTTTTTTTW",
      "TWTTTTTTTTTTTTTT",
      "TTTTTTTWTTTTWTTT",
      "TTTTWTTTTTTWTTTT",
      "TWTTTTTTTWTTTTTT",
      "TTTTTTTTTTTTTTWT",
      "TTTWTTTTWTTTTTTT",
      "TTTTTTTTTTTTTTTT",
      "TTTTTTTTTTTTTTTT",
    ],
  },
  {
    // Wooden plank bridge spanning a water gap between islands. Authored
    // HORIZONTAL (you walk left↔right across it): rail/support beams along the
    // top and bottom long edges (M = dark beam), a wood-plank deck (d = wood
    // light) with regular dark seams (D) every few columns, and a sliver of
    // ocean (v) peeking past each rail so it reads as crossing water. Vertical
    // bridges reuse this frame rotated 90° (see render-systems computeBridges).
    name: "tile/bridge-h",
    size: 16,
    pixels: [
      "vvvvvvvvvvvvvvvv",
      "MMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMM",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "MMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMM",
      "vvvvvvvvvvvvvvvv",
    ],
  },
  {
    name: "tile/fence-h",
    size: 16,
    pixels: [
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "mmmmmmmmmmmmmmmm",
      "WWWWWWWWWWWWWWWW",
      "mmmmmmmmmmmmmmmm",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
    ],
  },
  {
    name: "structure/market-wall",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWWM..",
      "..MWoooWoooWWM..",
      "..MWoooWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MWoWWWoooWWM..",
      "..MWoWWWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....DDDDDDDD....",
      "................",
    ],
  },
  {
    name: "structure/shopkeeper",
    size: 16,
    pixels: [
      "................",
      "......yyyy......",
      ".....yyyyyy.....",
      "....yyyyyyyy....",
      "...yyyyyyyyyy...",
      "..yyyyyyyyyyyy..",
      ".MMMMMMMMMMMMMM.",
      ".MWWoooWoooWWWM.",
      ".MWoWWWoWWoWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MWWWWWoWWWWWWM.",
      ".MWWWWoWoWWWWWM.",
      ".MWWWoWWWoWWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MMMMMMMMMMMMMM.",
      "....DDDDDDDD....",
    ],
  },
  {
    name: "tile/dirt",
    size: 16,
    pixels: [
      "DDDDDDDDDDDDDDDD",
      "DdDDdDDDDdDDdDDD",
      "DDDDDDDdDDDDDDDD",
      "DdDDDDDDDDDDDDdD",
      "DDDDDDDDDDdDDDDD",
      "DDdDDDDdDDDDDDDD",
      "DDDDDdDDDDDDdDDD",
      "DDDDDDDDDDDDDDDd",
      "DdDDDDDDDDDDDDDD",
      "DDDDDDDdDDDDdDDD",
      "DDDDdDDDDDDdDDDD",
      "DdDDDDDDDdDDDDDD",
      "DDDDDDDDDDDDDDdD",
      "DDDdDDDDdDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
    ],
  },
  {
    name: "farmer/conservative",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    // Speech-bubble icon rendered above farmers when a MEET fires.
    // White bubble with a dark outline and a yellow "!" exclamation mark inside.
    name: "indicator/meet",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Downward-pointing yellow arrow drawn above the head of the farmer the
    // camera is currently following (Pip or any clicked AI farmer). Bright
    // yellow body (y) with a dark outline (k) so it reads on any backdrop.
    name: "indicator/follow",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkkk.....",
      ".....kyyyyk.....",
      ".....kyyyyk.....",
      ".....kyyyyk.....",
      "...kkkyyyykkk...",
      "...kyyyyyyyyk...",
      "....kyyyyyyk....",
      ".....kyyyyk.....",
      "......kyyk......",
      ".......kk.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // ── Intention bubble glyphs (Brief 40) ─────────────────────────────────────
  // Each glyph is a small thought-bubble with a simple iconic fill rendered in
  // the EDG32 palette. All use: k=near-black outline, w=white bubble body,
  // with colour from existing SWATCH chars only.
  //
  // Legibility: 8×8 interior content area inside a 16×16 frame with a rounded
  // bubble outline and a small speech-bubble tail at the bottom-left.
  {
    // Plant seed — a small seed (brown dot) with two green leaf tips above.
    name: "indicator/intention-plant",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwlwwwk.....",
      "...kwwlwwwk.....",
      "...kwdwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Water — a blue droplet inside the bubble.
    name: "indicator/intention-water",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwewwwk.....",
      "...kwevevwk.....",
      "...kwevvewk.....",
      "...kwwvwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Harvest — a small wheat stalk (tan) inside the bubble.
    name: "indicator/intention-harvest",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwWwwk.....",
      "...kwwWWWwk.....",
      "...kwwwWwwk.....",
      "...kwwwlwwk.....",
      "...kwwwlwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Sell — a gold coin (circle) inside the bubble.
    name: "indicator/intention-sell",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwoowwk.....",
      "...kwoyoywk.....",
      "...kwwoowwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Buy — a small bag/sack (tan) inside the bubble.
    name: "indicator/intention-buy",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwkwwwk.....",
      "...kwWWWwwk.....",
      "...kwWoWwwk.....",
      "...kwWWWwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Travel — a small arrow (cream) pointing right, indicating movement.
    name: "indicator/intention-travel",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwqqqwk.....",
      "...kwwwqqqk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Sleep — a pair of Zs (cream) inside the bubble, indicating rest.
    name: "indicator/intention-sleep",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwqqqwk.....",
      "...kwwwqwwk.....",
      "...kwwqwwwk.....",
      "...kwwqqqwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Fish — a simple fish silhouette (blue) inside the bubble.
    name: "indicator/intention-fish",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwvvvwwk.....",
      "...kwvevwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Bid — a gavel/hammer (stone) inside the bubble, indicating auction.
    name: "indicator/intention-bid",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwqqwk.....",
      "...kwwwqqwk.....",
      "...kwwmmwwk.....",
      "...kwwmwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Meet (as intention) — two small dots facing each other, indicating social.
    name: "indicator/intention-meet",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwrwwrwk.....",
      "...kwrwwrwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Chop — a small axe head (stone/wood) inside the bubble.
    name: "indicator/intention-chop",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwqwwwk.....",
      "...kwqqwwwk.....",
      "...kwwqmwwk.....",
      "...kwwwmwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Mine — a pickaxe (stone head, wood handle) inside the bubble.
    name: "indicator/intention-mine",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwqwwk.....",
      "...kwwqqmwk.....",
      "...kwwwwmwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Work (NPC work) — a wrench/tool (stone) inside the bubble.
    name: "indicator/intention-work",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwqqwk.....",
      "...kwwqqqwk.....",
      "...kwwwqqwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Idle — three dots indicating the farmer is waiting.
    name: "indicator/intention-idle",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwqwqwqk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      ".....lllll......",
      "......lll.......",
      "......rrr.......",
      ".....rrrrr......",
      "......rrr.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      "....lllllll.....",
      ".....llLll......",
      "......lll.......",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      ".....rrrrr......",
      "......rrr.......",
      ".......r........",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lLl.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "......yoy.......",
      ".....yyyyo......",
      "......oyo.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....l...l.......",
      "...lLl.lLl......",
      "....l...l.......",
      ".....l.l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......l........",
      "......lLl.......",
      ".....ppppp......",
      "....ppppppp.....",
      "....ppppppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── brief 41 — new crop sprites ─────────────────────────────────────────────
  // Carrot (spring, fast). Orange body (o), green top (l/L).
  {
    name: "crop/carrot/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/carrot/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".....lLll.......",
      "......lll.......",
      "......ooo.......",
      "......ooo.......",
      ".......o........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/carrot/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....lLlll......",
      "......llll......",
      ".....ooooo......",
      "....ooooooo.....",
      "....ooooooo.....",
      ".....ooooo......",
      "......ooo.......",
      ".......o........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // Tomato (summer, mid). Red body (r), green leaf (l).
  {
    name: "crop/tomato/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/tomato/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "......lll.......",
      ".....lllll......",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/tomato/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "......lll.......",
      ".....lllll......",
      "......lll.......",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      ".....rrrrr......",
      "......rrr.......",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // Corn (summer, multi). Yellow stalk (y), gold cob (o).
  {
    name: "crop/corn/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/corn/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......y........",
      "......yly.......",
      ".......y........",
      ".......y........",
      "......yly.......",
      ".......y........",
      ".......y........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/corn/mature",
    size: 16,
    pixels: [
      "................",
      ".......y........",
      "......yly.......",
      ".......y........",
      "......yooy......",
      ".....yooooy.....",
      ".....yooooy.....",
      ".....yooooy.....",
      "......yooy......",
      ".......y........",
      ".......y........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // Grape (autumn, high-value). Purple/pumpkin color (p) on vine (l).
  {
    name: "crop/grape/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/grape/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....lllll......",
      "......lll.......",
      ".....l.l.l......",
      ".....ppp.p......",
      "......ppp.......",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/grape/mature",
    size: 16,
    pixels: [
      "................",
      "......lll.......",
      ".....lllll......",
      "....lllllll.....",
      "....l.ppp.l.....",
      "....lpppppl.....",
      "....lppppppl....",
      "....lpppppl.....",
      ".....l.ppp.l....",
      "......lllll.....",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // Winter-squash (winter). Tan body (W), green stem (l).
  {
    name: "crop/winter-squash/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/winter-squash/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....l...l.......",
      "...lLl.lLl......",
      "....l...l.......",
      ".....l.l........",
      "......WWW.......",
      ".......W........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/winter-squash/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......l........",
      "......lLl.......",
      ".....WWWWW......",
      "....WWWWWWW.....",
      "....WWWWWWW.....",
      "....WWWWWWW.....",
      ".....WWWWW......",
      "......WWW.......",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Tile floors ─────────────────────────────────────────────────────────────
  {
    name: "tile/forge-floor",
    size: 16,
    pixels: [
      "QQQQQQQQqQQQQQQQ",
      "QqQQQQQQQQQQqQQQ",
      "QQQQqQQQQQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "qQQQQQQqQQQQQQQQ",
      "QQQQQQQQQQQQqQQQ",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQQqQQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQQqQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/market-floor",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
    ],
  },
  {
    name: "tile/quarry-floor",
    size: 16,
    pixels: [
      "QQQqQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQqQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQqQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQQQQqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    // Darkened plank floor: face is wood-light (d) over near-black bark grout
    // (M), instead of the old tan-over-wood-dark. The new floor reads clearly
    // darker so the tan/wood carpenter tools and props pop against it rather
    // than blending in.
    name: "tile/wood-plank",
    size: 16,
    pixels: [
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
    ],
  },
  {
    // Sandy beach floor for the fishing isle — wet-sand tan (W) speckled with
    // lighter cream (w/T) grains, so it reads as a beach distinct from grass.
    name: "tile/sand",
    size: 16,
    pixels: [
      "WWWWWWWTWWWWWWWW",
      "WWWwWWWWWWWwWWWW",
      "WWWWWWWWWTWWWWWW",
      "WTWWWWWwWWWWWWTW",
      "WWWWWWWWWWWWWWWW",
      "WWWwWWWWTWWWWWwW",
      "WWWWWWWWWWWWWWWW",
      "WWWWWTWWWWWwWWWW",
      "WwWWWWWWWWWWWWTW",
      "WWWWWWWwWWWTWWWW",
      "WWWWWWWWWWWWWWWW",
      "WTWWWwWWWWWWWWWW",
      "WWWWWWWWWTWWWwWW",
      "WWWWWWWWWWWWWWWW",
      "WwWWWTWWWWwWWWWW",
      "WWWWWWWWWWWWWWTW",
    ],
  },
  {
    name: "tile/stone-floor",
    size: 16,
    pixels: [
      "QqQQQQqQQQQqQQQQ",
      "QQQQqQQQQQQQQQqQ",
      "qQQQQQQQqQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQqQQQ",
      "qQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQqQQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQqQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/ice-floor",
    size: 16,
    pixels: [
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
    ],
  },
  {
    name: "tile/mushroom-floor",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },

  // ── Structures ───────────────────────────────────────────────────────────────
  {
    name: "structure/blacksmith",
    size: 16,
    pixels: [
      "................",
      "..QQQQQQQQQQQQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQQQQQQQqqQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QQQQQQQQQQQQ..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....QQQQQQQQ....",
      "................",
    ],
  },
  {
    name: "structure/carpenter",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWwM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWWWWWWWWWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/fountain",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sSSSSSs.....",
      "....sSwwwSs.....",
      "....sSsssSSs....",
      ".....sSsSs......",
      "......sss.......",
      ".....sssss......",
      "....ssSSSSss....",
      "....sSSSSSSs....",
      "....sSSSSSSs....",
      "....ssSSSSss....",
      ".....ssssss.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/home",
    size: 16,
    pixels: [
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "...rrrrrrrrr....",
      "..MMMMMMMMMMMM..",
      "..MWWWoWWWoWWM..",
      "..MWWoWWWoWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/tree",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....CCCCC......",
      "....CCCCCCC.....",
      "...CCCCCCCCC....",
      "...CCCCCCCCC....",
      "....cCcCcCc.....",
      ".....CCCCC......",
      "......CCC.......",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "................",
      "................",
      "................",
    ],
  },
  {
    // brief 45 — autumn tree: same silhouette as structure/tree, canopy recolored
    // to golden/orange (a/A/b). Render-only variant selected in autumn.
    name: "structure/tree-autumn",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....aAaAa......",
      "....AaAbAaA.....",
      "...aAaAaAaAb....",
      "...AbAaAaAaA....",
      "....aAaAaAa.....",
      ".....AaAbA......",
      "......aAa.......",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "................",
      "................",
      "................",
    ],
  },
  {
    // brief 45 — bare winter tree: leafless branches + trunk, dusted with snow
    // (n) on the limbs. Render-only variant selected in winter.
    name: "structure/tree-bare",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....n..n.......",
      "....M.MM.M......",
      ".....MMMM.n.....",
      "...n..MM........",
      "....M.M.M.......",
      ".....MMM........",
      "......Mm........",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/stone",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....QQQQQQ.....",
      "....QQqqqQQQ....",
      "....QqQQQqQQ....",
      "....QQqqqQQQ....",
      "....QQQQQQQQQ...",
      ".....QQQQQQQ....",
      "......QQQQ......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/auction-podium",
    size: 16,
    pixels: [
      "................",
      "................",
      "....TTTTTTTT....",
      "....TooooooT....",
      "....TooooooT....",
      "....TooooooT....",
      "....ToooWooT....",
      "....ToooWooT....",
      "....TTTTTTTT....",
      ".....TTTTTT.....",
      "......TTTT......",
      ".......TT.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/notice-board",
    size: 16,
    pixels: [
      "................",
      "................",
      "....mmmmmmmm....",
      "....mWWWWWWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWWWWWWm....",
      "....mmmmmmmm....",
      ".......mm.......",
      ".......mm.......",
      ".......mm.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mill",
    size: 16,
    pixels: [
      "................",
      "......yyy.......",
      ".....yyyyy......",
      "....MMMMMMM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MMMMMMM.....",
      ".....mm.mm......",
      ".....mm.mm......",
      ".....mm.mm......",
      "....MMMMMMM.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/well",
    size: 16,
    pixels: [
      "................",
      "...m........m...",
      "...m..ssss..m...",
      "...mmssSSssm....",
      "....msSSSssm....",
      "....msSSSssm....",
      "....mssssssm....",
      "....QQQQQQQQ....",
      "....QQQQQQQQ....",
      ".....QQQQQQ.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // brief 50 — interactive shrine landmark: a ring of standing stones around a
    // dolmen (two upright megaliths capped by a dark lintel) with a small glowing
    // offering (gold/yellow) at its base and a grassy mound below. Reads as an
    // ancient sacred site distinct from every other structure. Stone light (q) /
    // dark (Q) for the megaliths, near-black (k) for the lintel + shadow seams,
    // gold (o) + yellow (y) for the offering glow, grass (G/c) for the mound.
    name: "structure/shrine",
    size: 16,
    pixels: [
      "................",
      "....kkkkkkkk....",
      "...kQQQQQQQQk...",
      "...kQqQQQQqQk...",
      "...QqQ....QqQ...",
      "...QqQ....QqQ...",
      "..q.QqQ..QqQ.q..",
      "..Q.QqQ..QqQ.Q..",
      "..q.QqQ..QqQ.q..",
      "...QqQ.yy.QqQ...",
      "...QqQ.oo.QqQ...",
      "..QqQ.yooy.QqQ..",
      "..QQQGooooGQQQ..",
      "...GGcGooGcGG...",
      "....cGGGGGGc....",
      "................",
    ],
  },
  {
    // brief 51 — heritage standing stones: an ancient dolmen ring. Three weathered
    // megaliths (stone light `q` faces, dark `Q` bodies) ring a low grassy mound
    // (`G`/`c`), with near-black `k` seams reading as age cracks/shadow. Distinct
    // from the shrine (no gold offering glow, an open ring rather than a capped
    // dolmen) and from every other structure. Purely decorative.
    name: "structure/heritage-stones",
    size: 16,
    pixels: [
      "................",
      ".....qq..qq.....",
      "....qQQkkQQq....",
      "....qQQkkQQq....",
      "..qq.QQQQ.qq....",
      ".qQQk.QQ.kQQq...",
      ".qQQk.QQ.kQQq...",
      ".qQQk....kQQq...",
      "..QQ......QQ....",
      "..QQ.qqqq.QQ....",
      "...k.qQQq.k.....",
      "...GGqQQqGG.....",
      "..GcGGGGGGcG....",
      "...GccGGccG.....",
      "....cGGGGc......",
      "................",
    ],
  },
  {
    // brief 51 — ruined watchtower: a broken stone tower (light `q` mortar over
    // dark `Q` blocks) with a jagged, collapsed crown and a fallen-block rubble
    // skirt at its base, near-black `k` for window slits / cracks. Reads as a
    // crumbling fortification — distinct from the well (no roof/bucket) and the
    // mill (no sails). Purely decorative.
    name: "structure/heritage-ruin",
    size: 16,
    pixels: [
      "................",
      "....Q..QQ.......",
      "....QqQQQq......",
      "....QqQQQq......",
      "....QqkQkq......",
      "....QqQQQq......",
      "....QqQQQq......",
      "....QqkQkq......",
      "....QqQQQq......",
      "...QQqQQQqQ.....",
      "...QqQQQQQq.....",
      "..QQqQQQQQqQ....",
      "..QqQQQQQQQq....",
      ".QQ.QQqqQQ.QQ...",
      "QQq..QQQQ..qQQ..",
      "................",
    ],
  },
  {
    // brief 51 — weathered statue: a robed figure on a plinth, carved in pale
    // stone (light `q` highlights, dark `Q` shade), near-black `k` for the worn
    // face/seams, atop a wide stepped pedestal. Reads as an old monument — the
    // tallest of the three relics. Purely decorative.
    name: "structure/heritage-statue",
    size: 16,
    pixels: [
      "................",
      "......qq........",
      ".....qkkq.......",
      ".....qQQq.......",
      "......qq........",
      ".....qQQq.......",
      "....qQqqQq......",
      "...qQ.qq.Qq.....",
      "....q.qq.q......",
      "......qq........",
      ".....qQQq.......",
      ".....QQQQ.......",
      "...QQQQQQQQ.....",
      "..QqqqqqqqqQ....",
      ".QQQQQQQQQQQQ...",
      "................",
    ],
  },
  {
    // brief 52 — waterfall BASE: the static rock/cliff the water falls over. A
    // mossy dark-stone gorge (stone dark `Q`, light `q`, near-black `k` seams, with
    // a little grass `G`/`c` cap on the clifftop) framing a recessed water channel
    // (ocean `v`, deep `V`) that ends in a foaming plunge pool (`e` ocean foam,
    // cream `w` froth) at the base. Drawn as the landmark; the bright animated
    // cascade streaks are layered ON TOP by the render loop (structure/waterfall-a/
    // b/c). Distinct from every other structure (a vertical gorge, not a tower or
    // ring). Purely decorative.
    name: "structure/waterfall",
    size: 16,
    pixels: [
      "..GcG......GcG..",
      ".QqkQ.vvvv.QkqQ.",
      ".QqkQ.vVVv.QkqQ.",
      ".QqkQ.vvvv.QkqQ.",
      ".QkQk.vVVv.kQkQ.",
      ".QqkQ.vvvv.QkqQ.",
      ".QqkQ.vVVv.QkqQ.",
      ".QkQk.vvvv.kQkQ.",
      ".QqkQ.vVVv.QkqQ.",
      ".QqkQ.vvvv.QkqQ.",
      ".QkQk.vVVv.kQkQ.",
      "..QkQ.vvvv.QkQ..",
      "...Q.ewwwe.Q....",
      "....ewwwwwe.....",
      "...eewwwwwee....",
      "....eeeeeee.....",
    ],
  },
  // Waterfall cascade — frame A. TRANSPARENT base; drawn OVER structure/waterfall
  // by the render loop as a wall-clock overlay (no determinism impact), exactly
  // like the forge-fire over the oven. Bright water-blue streaks (ocean foam `e`,
  // light `s`) occupy the cliff's central channel; across A→B→C the streak rows
  // STEP DOWN one row so the column reads as continuously falling water, with a
  // little lighter foam (`w`/`n`) at the plunge-pool base. EDG palette only.
  {
    name: "structure/waterfall-a",
    size: 16,
    pixels: [
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      ".....nwwwn......",
      "......nwn.......",
      "................",
      "................",
    ],
  },
  {
    name: "structure/waterfall-b",
    size: 16,
    pixels: [
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      ".....wnnw.......",
      ".....nwwwn......",
      "......nwn.......",
      "................",
    ],
  },
  {
    name: "structure/waterfall-c",
    size: 16,
    pixels: [
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......see.......",
      "......ees.......",
      "......nwn.......",
      ".....wnnw.......",
      ".....nwwwn......",
      "......nwn.......",
    ],
  },
  // ── Camping island (brief 54) ───────────────────────────────────────────────
  // The big TENT — island centerpiece. A wide canvas A-frame tent: cream/white
  // canvas (`w`) with red trim/banding (`r`), a dark triangular door opening (`k`)
  // and wood pole/peg detail (`d`/`D`) at the base, on a little grass apron
  // (`G`/`c`). Larger visual weight than the other landmarks — it fills most of
  // the 16×16 cell and reads clearly as a tent (a broad triangle, distinct from
  // the towers/rings/statues). Purely decorative; the rest effect is region-gated.
  {
    name: "structure/tent",
    size: 16,
    pixels: [
      "................",
      ".......w........",
      "......www.......",
      "......wrw.......",
      ".....wwrww......",
      ".....wwrww......",
      "....wwwrwww.....",
      "....wwrkrww.....",
      "...wwwrkrwww....",
      "...wwrrkrrww....",
      "..wwwrrkrrwww...",
      "..wrwrrkrrwrw...",
      ".dwwwwrkrwwwwd..",
      ".DGcwwwwwwwcGD..",
      "..GGcGGGGGcGG...",
      "...cGGGGGGGc....",
    ],
  },
  // Campfire — static BASE (the spawned landmark). A ring of stones (`Q`/`q`)
  // around two crossed logs (`d`/`D`) with a small resting ember (`r`/`o`). The
  // animated flame (campfire-a/b/c) is layered ON TOP by the render loop as a
  // wall-clock overlay (no determinism impact), exactly like the forge fire over
  // the oven. EDG palette only (fire reds/oranges + wood + stone).
  {
    name: "structure/campfire",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "......ror.......",
      ".....rooor......",
      "....Q.dDd.Q.....",
      "...Qq.DdD.qQ....",
      "...Qq.dDd.qQ....",
      "....QqqqqqQ.....",
      ".....QQQQQ......",
      "................",
      "................",
      "................",
    ],
  },
  // Campfire flame — frame A. TRANSPARENT base; drawn OVER structure/campfire by
  // the render loop (wall-clock overlay, no sim/determinism impact), like the
  // forge fire over the oven. Flames: r (rust/base) → o (gold) → y (yellow tip).
  // Across A→B→C the flame shape + brightness vary so the fire flickers.
  {
    name: "structure/campfire-a",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      ".......y........",
      ".......o........",
      "......yoy.......",
      "......oyo.......",
      ".....rooor......",
      ".....rooor......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/campfire-b",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......y........",
      "......y.y.......",
      ".......o........",
      "......yoy.......",
      ".....yooooy.....",
      ".....rooyor.....",
      ".....rooooor....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/campfire-c",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      ".......y........",
      "......yoy.......",
      ".....y.o.y......",
      "......yoy.......",
      ".....rooor......",
      ".....rooyor.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mushroom-marker",
    size: 16,
    pixels: [
      "................",
      "................",
      "......ppp.......",
      ".....ppppp......",
      "....ppwpppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      ".......l........",
      ".......l........",
      ".......l........",
      "......lll.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/ice-marker",
    size: 16,
    pixels: [
      "................",
      "......s.........",
      ".....sss........",
      "..s..sss..s.....",
      ".sss.sss.sss....",
      "sssssssssssss...",
      ".sss.sss.sss....",
      "..s..sss..s.....",
      ".....sss........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Workshop props — blacksmith forge ───────────────────────────────────────
  // Stationary decorations placed around the blacksmith. The NPC walks between
  // them and plays a pose (see ACTION_TEMPLATES hammer). The oven's fire is an
  // animated overlay (forge/fire-a/b/c) cycled by the render loop, drawn ABOVE
  // the static oven body so the flames flicker over a stable hearth.

  // Stone-and-brick oven/hearth with a dark mouth. The fire overlay sits in the
  // mouth (rows 6–9). Body uses stone (Q/q) + brick rust (r) + dark mouth (k).
  {
    name: "structure/forge-oven",
    size: 16,
    pixels: [
      "................",
      "....QQQQQQQQ....",
      "...QqqqqqqqqQ...",
      "...QqrqrqrqqQ...",
      "...QqqqqqqqqQ...",
      "...QkkkkkkkkQ...",
      "...Qkk....kkQ...",
      "...Qk......kQ...",
      "...Qk......kQ...",
      "...Qkk....kkQ...",
      "...QkkkkkkkkQ...",
      "...QqrqrqrqqQ...",
      "...QQQQQQQQQQ...",
      "....mm....mm....",
      "....MM....MM....",
      "................",
    ],
  },
  // Forge fire — frame A. Transparent base; drawn over forge-oven's mouth.
  // Flames: r (rust/base) → o (gold) → y (yellow tip). Cycled A→B→C.
  {
    name: "structure/forge-fire-a",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".....r..r.r.....",
      ".....ro.ror.....",
      ".....oyooyo.....",
      ".....royyor.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-fire-b",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......r........",
      ".....r.oo.r.....",
      ".....royyor.....",
      ".....oyyyyo.....",
      ".....royyor.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-fire-c",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......r.r.......",
      ".....ror.r......",
      ".....oyoroo.....",
      ".....oyyyyo.....",
      ".....royoyr.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Anvil on a wooden stump. Steel face (q) + dark body (Q), horn to the left,
  // mounted on a brown stump (m/M). The NPC hammers facing this.
  {
    name: "structure/anvil",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "......qqqqq.....",
      "....qqQQQQQq....",
      "...QQQQQQQQQ....",
      "....QQQQQQQ.....",
      ".....QQQ........",
      ".....QQQQ.......",
      "....QQQQQQ......",
      "....mmmmmm......",
      "....mMMMMm......",
      "....mMMMMm......",
      "....MMMMMM......",
      "................",
    ],
  },
  // Quench tub — barrel of water for cooling hot metal. Wood staves (m/M) with
  // metal hoops (Q) and a water surface (v/e highlights).
  {
    name: "structure/quench-tub",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....QQQQQQQQ....",
      "....mvvevvvm....",
      "....mvvvvevm....",
      "....mevvvvvm....",
      "....QQQQQQQQ....",
      "....mMMMMMMm....",
      "....mMMMMMMm....",
      "....QQQQQQQQ....",
      "....mMMMMMMm....",
      "....mMMMMMMm....",
      "....MMMMMMMM....",
      "................",
      "................",
    ],
  },
  // Tool rack — hammers + tongs hung on a wooden wall board.
  {
    name: "structure/tool-rack",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWWM..",
      "..M.q..Q..q..M..",
      "..M.q..Q..Q..M..",
      "..M.m..m..m..M..",
      "..M.m..m..mm.M..",
      "..M.m..m..m..M..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Workshop props — carpenter ───────────────────────────────────────────────
  // Sturdy workbench with a plank top (W) on dark legs (M), a saw (q) resting on
  // it, and a couple of pegs.
  {
    name: "structure/workbench",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....qqqqqq.....",
      "....q......q....",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..MWWWWWWWWWWM..",
      "..M..........M..",
      "..M..........M..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "................",
      "................",
    ],
  },
  // Sawhorse with a log being cut. X-legs (m) + crossbar, a log (d/D) on top.
  {
    name: "structure/sawhorse",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....dddddddd....",
      "...dDdDdDdDdd...",
      "....dddddddd....",
      "..mmmmmmmmmmmm..",
      "...m.m....m.m...",
      "...m.m....m.m...",
      "..m...m..m...m..",
      "..m...m..m...m..",
      ".m....m..m....m.",
      ".m....m..m....m.",
      "................",
      "................",
      "................",
    ],
  },
  // Log pile — stacked round logs (end-grain).
  {
    name: "structure/log-pile",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....dddd.dddd...",
      "...dDmDddDmDd...",
      "...dDmDddDmDd...",
      "....dddd.dddd...",
      "..dddd.dddd.dd..",
      ".dDmDddDmDddDm..",
      ".dDmDddDmDddDm..",
      "..dddd.dddd.dd..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Plank stack — sawn lumber stacked flat.
  {
    name: "structure/plank-stack",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "................",
      "................",
      "................",
    ],
  },

  // ── Farmer action poses (generated) ─────────────────────────────────────────
  // Action templates are authored once in conservative palette chars:
  //   head=y, shirt=r, legs=D, face=w, eyes=k.
  // Tool chars (m=brown handle, q=stone light, Q=stone dark, W=tan/wood,
  //             o=gold/seed, s=water blue-lt, e=water blue-hi) are NOT
  //   substituted, so they keep their colour across all personalities.
  //
  // Substitution maps applied per personality (in listed order):
  //   conservative: identity
  //   aggressive:   y→k, D→k
  //   hoarder:      y→D, r→y
  //   opportunist:  y→s, r→S, D→k
  //
  // The generator at the bottom of this file expands all 4 personalities ×
  // 7 actions (till/water/refill/chop/mine/plant/work) and pushes them in.
  // ──────────────────────────────────────────────────────────────────────────

  // ── Decorations ──────────────────────────────────────────────────────────────
  {
    name: "decoration/scarecrow",
    size: 16,
    pixels: [
      "................",
      "........m.......",
      ".......mmm......",
      "........m.......",
      "......yyyyy.....",
      ".......yyy......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/windmill",
    size: 16,
    pixels: [
      "................",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......Q........",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......m........",
      ".......m........",
      ".......m........",
      "......mmm.......",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/flower-bed",
    size: 16,
    pixels: [
      "................",
      "................",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....cccccccc....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/fence-art",
    size: 16,
    pixels: [
      "................",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWoWoWoWoWoWoWm.",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Debug ────────────────────────────────────────────────────────────────────
  {
    name: "debug/player",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rwwwwwr.....",
      "....rk.w.kr.....",
      "....rrwwwr......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },

  // ── Carpentry floor — laid stone slabs ───────────────────────────────────────
  // Replaces the old dark wood-plank carpenter floor with a stonemason-style
  // slab floor: light stone faces (q) bordered by dark stone grout (Q), in an
  // offset-brick pattern so it reads as a worked-stone workshop floor distinct
  // from the speckled tile/stone-floor used by the mill/wells.
  {
    name: "tile/carpentry-floor",
    size: 16,
    pixels: [
      "QQQQQQQQQQQQQQQQ",
      "QqqqqqqQqqqqqqqQ",
      "QqqqqqqQqqqqqqqQ",
      "QqqqqqqQqqqqqqqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqqqQqqqqqqqQqqQ",
      "QqqqQqqqqqqqQqqQ",
      "QqqqQqqqqqqqQqqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqqqqqqQqqqqqqqQ",
      "QqqqqqqQqqqqqqqQ",
      "QqqqqqqQqqqqqqqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqqqQqqqqqqqQqqQ",
      "QqqqQqqqqqqqQqqQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },

  // ── Fishing ──────────────────────────────────────────────────────────────────
  // Fishing spot — THREE rising bubbles animated over a 3-frame cycle (A→B→C),
  // drawn on its non-walkable ocean tile (layer 4). Each frame the three bubbles
  // climb a little higher and grow, then pop into a foam crest at the top and
  // restart from the seabed — a looping "glug glug" of bubbles rising to the
  // surface so the spot reads as fish stirring the water. The three bubbles sit
  // in three columns (left/center/right) and are staggered in phase so they
  // don't rise in lockstep. Transparent base (.) so the ocean shows through;
  // q = soft bubble outline (light stone), e = bright ocean-foam ring/body,
  // w = white highlight + foam crest where a bubble pops at the surface.
  // `structure/fishing-spot` is frame A — it is the frame the BubbleSystem
  // spawns + the snapshot carries; the render loop swaps in -a/-b/-c for the
  // animation (see main.ts).
  //
  // Frame A — bubbles low (near the seabed), small.
  {
    name: "structure/fishing-spot",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "...q........q...",
      "..qeq......qeq..",
      "...q...qq...q...",
      ".......qeq......",
      "........q.......",
      "................",
      "................",
    ],
  },
  // Frame B — bubbles risen to mid-tile, a touch bigger; the center one larger.
  {
    name: "structure/fishing-spot-b",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "...qq.......q...",
      "..qewq.....qeq..",
      "..qeeq....qewq..",
      "...qq......qq...",
      "................",
      ".......qq.......",
      "......qewq......",
      "......qeeq......",
      ".......qq.......",
      "................",
      "................",
      "................",
    ],
  },
  // Frame C — bubbles reach the top and POP into foam crests (w); a fresh small
  // bubble starts again at the bottom so the loop reads as continuous.
  {
    name: "structure/fishing-spot-c",
    size: 16,
    pixels: [
      "...w........w...",
      "..wew......wew..",
      "...w........w...",
      "................",
      "................",
      "................",
      "................",
      ".......w........",
      "......wew.......",
      ".......w........",
      "................",
      "................",
      "................",
      "...q.......qq...",
      "..qeq.....qewq..",
      "...q.......qq...",
    ],
  },
  // ── Coral (deep-water seabed zones) ──────────────────────────────────────────
  // A coral zone is a CONNECTED seabed patch made of many tiles that blend into
  // ONE continuous texture (not independent per-tile stamps). It reads as
  // something resting DEEP under the water — drawn on NON-walkable ocean tiles
  // at low alpha (see `computeCoral` → CORAL_ALPHA) so the flowing water shows
  // through and it looks murky/submerged. The palette is deliberately
  // blue-shifted and desaturated: deep ocean (V), structure-blue (S/s) and
  // muted stone (Q) for the bulk, with only faint hints of dark leaf (l) for
  // kelp and a single dull-gold (o) polyp as an accent — no vivid reds/oranges.
  //
  // It's an autotile set, like the island walls/shores: `computeCoral` picks a
  // FILL tile for cluster INTERIOR cells (covers the whole tile edge-to-edge so
  // neighbours seam together into one mass) and an EDGE tile for cluster BORDER
  // cells (the seabed fades to water on the open side; authored top-fade-up and
  // rotated 0/90/180/270 to face the open water). Adjacent fill tiles meet with
  // no seam, so a multi-tile zone looks like one big reef rather than tiles.

  // FILL — full-bleed seabed, used for interior cells. Edges are solid muted
  // blue on all four sides so neighbouring fills join seamlessly; the surface is
  // a gentle mottle of structure-blue (S/s) over deep ocean (V) with sparse
  // stone lumps (Q) and one dull-gold polyp (o) so the mass has texture.
  {
    name: "tile/coral-fill",
    size: 16,
    pixels: [
      "SSSSSSSSSSSSSSSS",
      "SsSSSVSSSSVSSSsS",
      "SSSSSSSsSSSSSSSS",
      "SSVSSSSSSSSVSSQS",
      "SsSSSSQSSSSSSSSS",
      "SSSSSSSSSSsSSSSS",
      "SSSVSSSSSSSSSVSS",
      "SSSSSSoSSSSSSSSS",
      "SSsSSSSSSSQSSSsS",
      "SSSSSVSSSSSSSSSS",
      "SQSSSSSSSsSSSSSS",
      "SSSSSSSSSSSSVSSS",
      "SSSVSSSsSSSSSSQS",
      "SsSSSSSSSSVSSSSS",
      "SSSSQSSSSSSSSSsS",
      "SSSSSSSSSSSSSSSS",
    ],
  },
  // EDGE — seabed that fills the BOTTOM of the tile and FADES upward into open
  // water along the TOP edge, so a cluster border softly dissolves into the sea.
  // Authored top-fade-up; `computeCoral` rotates it to face whichever side is
  // open water. Top rows thin out to v/V water; lower rows are solid seabed that
  // seams with an adjacent fill below.
  {
    name: "tile/coral-edge",
    size: 16,
    pixels: [
      "vVvVvVvVvVvVvVvV",
      "vVvVvVvVvVvVvVvV",
      "VvSVvVvVvVvVvSvV",
      "vSVSvVSVvVSvSVSv",
      "VSSVSvSSVSvSSVSV",
      "SSVSSSSVSSSSVSSS",
      "SSSSSSoSSSSSSSSS",
      "SsSSSSSSSSQSSSsS",
      "SSSSSSSSSSSSSSSS",
      "SSSVSSSsSSSSSVSS",
      "SQSSSSSSSsSSSSSS",
      "SSSSSSSSSSSSVSSS",
      "SSSVSSSsSSSSSSQS",
      "SsSSSSSSSSVSSSSS",
      "SSSSQSSSSSSSSSsS",
      "SSSSSSSSSSSSSSSS",
    ],
  },
  // CORNER — an INNER cluster cell that has open water on TWO adjacent sides
  // (a convex corner of the patch). Fades to water across the TOP-LEFT quadrant;
  // rotated by `computeCoral` so the fade faces the open corner. Keeps the
  // patch's rounded corners from looking like a hard staircase of edge tiles.
  {
    name: "tile/coral-corner",
    size: 16,
    pixels: [
      "vVvVvVvVvVvVvVvV",
      "vVvVvVvVvVvVvSvV",
      "vVvVvVvVvVvSVSvV",
      "vVvVvVvVvSvSVSSv",
      "vVvVvVvSvSVSSVSV",
      "vVvVvSvSSSSVSSSS",
      "vVvSvSSSSSoSSSSS",
      "vSvSVSSSSSSSSQsS",
      "vVSSSSSSSSSSSSSS",
      "vSSSVSSSsSSSSSVS",
      "SSQSSSSSSSsSSSSS",
      "SSSSSSSSSSSSVSSS",
      "SSSVSSSsSSSSSSQS",
      "SsSSSSSSSSVSSSSS",
      "SSSSQSSSSSSSSSsS",
      "SSSSSSSSSSSSSSSS",
    ],
  },

  // Fishing rod — wooden pole (m/d) with a line (q) and a gold hook glint (o).
  {
    name: "tool/fishing-rod",
    size: 16,
    pixels: [
      "................",
      ".............dq.",
      "............d..q",
      "...........d...q",
      "..........d...q.",
      ".........d..oq..",
      "........d.......",
      ".......d........",
      "......d.........",
      ".....d..........",
      "....m...........",
      "...m............",
      "..m.............",
      ".m..............",
      "m...............",
      "................",
    ],
  },
  // Fish — three kinds, ascending value. minnow (small/grey), bass (green),
  // salmon (red/orange). Used for inventory/feed flavour; the catch flow itself
  // banks gold directly.
  {
    name: "fish/minnow",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".....qqq.....Q..",
      "...qqqqqqq..QQ..",
      "..qqqqqqqqqQQ...",
      "..qqqkqqqqqQ....",
      "...qqqqqqq..Q...",
      ".....qqq........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "fish/bass",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......GGG....l..",
      "....GGGGGGG.ll..",
      "...GGGGGGGGlll..",
      "..GGGGGGGGGGll..",
      "..GGGkGGGGGGl...",
      "..GGGGGGGGGGll..",
      "...GGGGGGGGlll..",
      "....GGGGGGG.ll..",
      "......GGG....l..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "fish/salmon",
    size: 16,
    pixels: [
      "................",
      "................",
      "......rrr....p..",
      "....rrrrrrr.pp..",
      "...rrrrrrrrppp..",
      "..rrrrrrrrrrpp..",
      ".rrrrrrrrrrrp...",
      ".rrrkrrrrrrrpp..",
      ".rrrrrrrrrrrp...",
      "..rrrrrrrrrrpp..",
      "...rrrrrrrrppp..",
      "....rrrrrrr.pp..",
      "......rrr....p..",
      "................",
      "................",
      "................",
    ],
  },

  // ── Extra decorations & detail props ─────────────────────────────────────────
  // A small library of static dressing the world can scatter for visual
  // interest. All EDG32-palette, 16×16, layer 40 (below NPCs/farmers).
  {
    // Wooden barrel with metal hoops.
    name: "decoration/barrel",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....dddddd......",
      "...dDDDDDDd.....",
      "...dddddddd.....",
      "...kkkkkkkk.....",
      "...dddddddd.....",
      "...dDDDDDDd.....",
      "...dddddddd.....",
      "...kkkkkkkk.....",
      "...dddddddd.....",
      "...dDDDDDDd.....",
      "....dddddd......",
      "................",
      "................",
    ],
  },
  {
    // Wooden crate with cross-bracing.
    name: "decoration/crate",
    size: 16,
    pixels: [
      "................",
      "................",
      "...dddddddd.....",
      "...dDdddddDd....",
      "...ddDdddDdd....",
      "...dddDdDddd....",
      "...ddddDdddd....",
      "...dddDdDddd....",
      "...ddDdddDdd....",
      "...dDdddddDd....",
      "...dddddddd.....",
      "...dddddddd.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Clay pot brimming with leafy plant.
    name: "decoration/potted-plant",
    size: 16,
    pixels: [
      "................",
      "......LlL.......",
      ".....LLlLL......",
      "....LlLLlLl.....",
      ".....LLlLL......",
      "......LLL.......",
      ".......l........",
      ".....rrrrr......",
      ".....rrrrr......",
      "......rrr.......",
      "......rrr.......",
      ".......r........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Lamp post — a warm lantern on a stone post (atmosphere for the village).
    name: "decoration/lamp-post",
    size: 16,
    pixels: [
      "................",
      ".......k........",
      "......kok.......",
      "......oyo.......",
      "......oyo.......",
      "......kok.......",
      ".......Q........",
      ".......Q........",
      ".......Q........",
      ".......Q........",
      ".......Q........",
      ".......Q........",
      "......QQQ.......",
      ".....QQQQQ......",
      "................",
      "................",
    ],
  },
  {
    // Wooden signpost with a painted arrow.
    name: "decoration/signpost",
    size: 16,
    pixels: [
      "................",
      "................",
      "...WWWWWWWW.....",
      "...WkkkkkkW.....",
      "...WkwwwwkW.....",
      "...WWWWWWWW.....",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "......mmm.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Round hay bale.
    name: "decoration/hay-bale",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....WWWWWW......",
      "...WyWyWyWW.....",
      "..WyWWyWWyWW....",
      "..WWyWWyWWyW....",
      "..WyWWyWWyWW....",
      "..WWyWWyWWyW....",
      "..WyWWyWWyWW....",
      "...WWyWWyWW.....",
      "....WWWWWW......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Small bush / shrub.
    name: "decoration/bush",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....lll........",
      "...llLLLll......",
      "..lLLLLLLLl.....",
      ".lLLLLgLLLLl....",
      ".lLLgLLLLgLl....",
      ".lLLLLLLLLLl....",
      "..lLLLLLLLl.....",
      "...llLLLll......",
      ".....lll........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Stack of firewood logs.
    name: "decoration/log-stack",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "...MdMdMdMd.....",
      "...dMdMdMdM.....",
      "...MdMdMdMd.....",
      "...dMdMdMdM.....",
      "...MdMdMdMd.....",
      "...dMdMdMdM.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Big workshop buildings (multi-tile, 32×48) ───────────────────────────────
  // LARGE bottom-anchored scenery that anchors each craftsman island with a real
  // building behind the work-yard. They are STATIC (never move), so they're baked
  // into the static layer (render-systems iterStaticSprites / BIG_STRUCTURES) and
  // drawn bottom-aligned to their base tile.
  //
  // Authoring: 32 wide × 48 tall (2 tiles wide × 3 tall). The bottom 16px is the
  // ground footprint (the tile it "stands on"); rows above are overhang that draw
  // up/behind nearer entities. Lower-Y rows are the roof/upper storey; the door
  // sits at the base so the NPC + yard props in front read as the forge/shop yard.

  // Blacksmith forge-house — stone-and-timber smithy with a brick chimney, a
  // pitched slate roof, a glowing forge window, and a timber double door.
  // Q/q = stone walls, S/s = slate roof, r = brick chimney, M/m/D/d = timber,
  // o/y = forge glow through the window, k = dark openings.
  {
    name: "structure/forge-house",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "..........rrrr..................",
      "..........rkkr..................",
      "..........rkkr..................",
      "..........rrrr..................",
      "..........rQQr..................",
      ".........SSSSSSS................",
      "........SSSSSSSSS...............",
      ".......SSSSSSSSSSS..............",
      "......SSSSSSSSSSSSS.............",
      ".....SSSSSSSSSSSSSSS............",
      "....SSSSSSSSSSSSSSSSS...........",
      "...SSsSSsSSsSSsSSsSSsS..........",
      "..SSSSSSSSSSSSSSSSSSSSS.........",
      ".sSSSSSSSSSSSSSSSSSSSSSs........",
      "QQQQQQQQQQQQQQQQQQQQQQQQ........",
      "QqqqqqqqqqqqqqqqqqqqqqqQ........",
      "QqQQQQQQQQQQQQQQQQQQQQqQ........",
      "QqQ.........QQQ.....QQqQ........",
      "QqQ.ooooo...QQQ.QQQ.QQqQ........",
      "QqQ.oyyyo...QQQ.QkQ.QQqQ........",
      "QqQ.oyoyo...QQQ.QkQ.QQqQ........",
      "QqQ.oyyyo...QQQ.QkQ.QQqQ........",
      "QqQ.ooooo...QQQ.QkQ.QQqQ........",
      "QqQ.........QQQ.QkQ.QQqQ........",
      "QqQQQQQQQQQQQQQ.QkQ.QQQqQ.......",
      "QqqqqqqqqqqqqQ..QkQ..qqqQ.......",
      "QqQQQQQQQQQQQQ..QkQ.QQQqQ.......",
      "QqQDDDDDDDDDDD..QkQ.DDDqQ.......",
      "QqQDdddddddddD..QkQ.DddQ........",
      "QqQDddddddddDD..QkQ.DddQ........",
      "QqQDdDDDDDDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QqQDdDddddDDdD..QkQ.DddQ........",
      "QQQQQQQQQQQQQQQQQQQQQQQQ........",
      "kQQQQQQQQQQQQQQQQQQQQQQk........",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },

  // Carpenter's workshop — timber lumber-mill with a green pitched roof, two
  // shuttered windows, a plank-clad facade, and a wide barn door showing dark
  // rafters. G/g/l/L = green roof, W/w = tan planks, M/m/D/d = timber frame,
  // q = window-glint, k = open doorway shadow.
  {
    name: "structure/carpenter-workshop",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "................................",
      ".............ll.................",
      "............lLLl................",
      "...........lLLLLl...............",
      "..........lLGGGGLl..............",
      ".........lLGGGGGGLl.............",
      "........lLGGGGGGGGLl............",
      ".......lLGGGGGGGGGGLl...........",
      "......lLGGGGGGGGGGGGLl..........",
      ".....lLGGGGGGGGGGGGGGLl.........",
      "....lLGGgGGgGGgGGgGGgGLl........",
      "...lLGGGGGGGGGGGGGGGGGGLl.......",
      "..lLGGGGGGGGGGGGGGGGGGGGLl......",
      ".lLGGGGGGGGGGGGGGGGGGGGGGLl.....",
      "lLLLLLLLLLLLLLLLLLLLLLLLLLLl....",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMM....",
      "MWWWWWWWWWWWWWWWWWWWWWWWWWWM....",
      "MWMWWWWWWWWWWWWWWWWWWWWWWMWM....",
      "MWMW..mmmm.WWWWWWWW.mmmm.WMW....",
      "MWMW.mWWWWm.WWWWWW.mWWWWm.WM....",
      "MWMW.mWqqWm.WWWWWW.mWqqWm.WM....",
      "MWMW.mWqqWm.WWWWWW.mWqqWm.WM....",
      "MWMW.mWWWWm.WWWWWW.mWWWWm.WM....",
      "MWMW..mmmm.WWWWWWWW.mmmm.WMW....",
      "MWMWWWWWWWWWWWWWWWWWWWWWWMWM....",
      "MWMWWWWWWWkkkkkkkkWWWWWWWMWM....",
      "MWMWWWWWWWkddddddkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MWMWWWWWWWkdDDDDdkWWWWWWWMWM....",
      "MMMMMMMMMMkdDDDDdkMMMMMMMMM.....",
      "kMMMMMMMMMkkkkkkkkMMMMMMMMk.....",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },

  // ── Extra blacksmith yard detail props (16×16) ───────────────────────────────
  // Grindstone — round whetstone on a wooden frame for sharpening blades.
  {
    name: "structure/grindstone",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....QQQQ.......",
      "....QqqqqQ......",
      "...QqQQQQqQ.....",
      "...QqQkkQqQ.....",
      "...QqQkkQqQ.....",
      "...QqQQQQqQ.....",
      "....QqqqqQ......",
      "....mQQQQm......",
      "...mm....mm.....",
      "..mm......mm....",
      "..m........m....",
      "..m........m....",
      "................",
      "................",
    ],
  },
  // Coal pile — heap of black coal/coke for the forge, a few embers glowing.
  {
    name: "structure/coal-pile",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "......kk........",
      ".....kkkk.......",
      "....kkokkk......",
      "...kkkkkokk.....",
      "..kkokkkkkkk....",
      "..kkkkkokkkk....",
      ".kkkkkkkkkokk...",
      ".kkokkkkkkkkk...",
      "kkkkkkkokkkkkk..",
      "................",
      "................",
      "................",
    ],
  },
  // Iron ingot rack — finished bars stacked on a timber rack. Steel q/Q + wood.
  {
    name: "structure/ingot-rack",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "..M........M....",
      "..MqqqqqqqqM....",
      "..MQQQQQQQQM....",
      "..MqqqqqqqqM....",
      "..MQQQQQQQQM....",
      "..MqqqqqqqqM....",
      "..MQQQQQQQQM....",
      "..MMMMMMMMMM....",
      "...m......m.....",
      "...m......m.....",
      "................",
      "................",
      "................",
    ],
  },

  // ── Extra carpenter yard detail props (16×16) ────────────────────────────────
  // Lumber rack — a frame holding long boards on end, leaning at angles.
  {
    name: "structure/lumber-rack",
    size: 16,
    pixels: [
      "................",
      ".W..W.W..W..W...",
      ".W..W.W..W..W...",
      ".W..W.W..W.W....",
      ".W.W..W.W..W....",
      ".W.W..W.W.W.....",
      ".WW...WW.W.W....",
      "MMMMMMMMMMMMM...",
      ".WW...WW..WW....",
      ".W.W..W.W..W....",
      ".W..W.W..W.W....",
      "MMMMMMMMMMMMM...",
      "..m........m....",
      "..m........m....",
      "................",
      "................",
    ],
  },
  // Sawpit — a pit with a two-man saw and sawdust, for ripping logs into planks.
  {
    name: "structure/sawpit",
    size: 16,
    pixels: [
      "................",
      "................",
      "...dddddddd.....",
      "..dDdDdDdDdd....",
      "..dddddddddd....",
      "..qqqqqqqqqq....",
      "..mkkkkkkkkm....",
      "..mkWWkkWWkm....",
      "..mkkkkkkkkm....",
      "..mkWkkkkWkm....",
      "..mkkkkkkkkm....",
      "..mmmmmmmmmm....",
      "...WWWWWWWW.....",
      "...WW.WW.WW.....",
      "................",
      "................",
    ],
  },
  // Wood-shavings pile — curls of plane shavings + a couple of off-cuts.
  {
    name: "structure/shavings-pile",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......WdW.......",
      ".....WdWdW......",
      "....WdWWWdW.....",
      "...WdWdWdWdW....",
      "..WdWWdWWdWdW...",
      "..dWdWdWdWdWd...",
      "...WWdWWdWWW....",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── brief 48 — Boats & Coral Fishing static decorations ────────────────────
  // structure/boat — a moored rowboat at the dock tile (south edge of each
  // fishing isle). Top-down perspective: wood hull (d/D), dark outline/shadow
  // (M/k), a pair of oars (m), and shallow ocean reflections (v/e) on either
  // side so the boat reads as floating. Purely static — the boat never moves.
  {
    name: "structure/boat",
    size: 16,
    pixels: [
      "................",
      "....vvvvvvvv....",
      "...vvDDDDDDvv...",
      "...vDddddddDv...",
      "...vDddmdddDv...",
      "...vDdmmmddDv...",
      "...vDddmdddDv...",
      "...vDddddddDv...",
      "...vvDDDDDDvv...",
      "....vevvvvev....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // tile/coral-reef — the FISHABLE reef marker. Brighter and richer than the
  // background decorative tile/coral-* tiles so the reef reads as a distinct
  // "go here to fish" location. Ocean base (V/v), vivid gold polyps (o),
  // red coral branches (r), bright foam highlights (e/w), stone lumps (Q)
  // for texture. Full-bleed so it tiles cleanly with the ocean around it.
  {
    name: "tile/coral-reef",
    size: 16,
    pixels: [
      "VVVeVVVVVVeVVVVV",
      "VVVVVVVeVVVVVVVV",
      "VeVVVrVVVVVrVVeV",
      "VVVVrrrrVVrrrrVV",
      "VVVrroorrVoorrVV",
      "VVVrrooorroorvVV",
      "VeVVrroooorrvVeV",
      "VVVVrroooorrVVVV",
      "VVVVVrroorrVVVVV",
      "VVeVVVrrrrVVeVVV",
      "VVVVVVVrrVVVVVVV",
      "VVVVVVoooVVVVVVV",
      "VVVeVoooooVeVVVV",
      "VVVVVowoooVVVVVV",
      "VVVVVVoooVVVVVVV",
      "VVVeVVVVVVeVVVVV",
    ],
  },

  // ── Forge chimney smoke (animated overlay, drawn above the forge-house) ───────
  // Three frames of a rising smoke puff, cycled by the render loop like the forge
  // fire. Transparent base; s/S = steel/slate smoke greys, drifting up.
  {
    name: "structure/forge-smoke-a",
    size: 16,
    pixels: [
      "......ss........",
      ".....sSSs.......",
      ".....sSSs.......",
      "......ss........",
      "......s.........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-smoke-b",
    size: 16,
    pixels: [
      ".....sSs........",
      "....sSSSs.......",
      "....sSSSs.......",
      ".....sSs........",
      "......ss........",
      "......s.........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-smoke-c",
    size: 16,
    pixels: [
      "....sSSs........",
      "...sSSSSs.......",
      "...sSSSSs.......",
      "....sSs.........",
      "....sSs.........",
      ".....ss.........",
      "......s.........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
];
