import { type PixelRecipe } from "./types";

// Tool chars (m q Q W o s e) are excluded from substitution so they keep their colour across all personalities.

export const ACTION_TEMPLATES: Record<string, readonly string[]> = {
  work: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r.rrr.......",
    "....rr..........",
    "...DDD..........",
    "...DDD..........",
    "................",
    "................",
  ],

  till: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrr.......",
    "..rrrrrrrrm.....",
    "..rrwwwrrmm.....",
    "...r....mm......",
    "...r...mm.......",
    "..DDD.Qm........",
    "..DDD..Q........",
    "................",
    "................",
  ],

  water: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrrr......",
    "..rrrrrrrrr.....",
    "..rrwwwrrQQQ....",
    "...r....qQQ.....",
    "..DDD....s.s....",
    "..DDD.....s.....",
    "...........s....",
    "................",
    "................",
  ],

  refill: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrrr......",
    "...rrrrrrrrQQ...",
    "...rrwwwrqqQ....",
    "....r....qQ.....",
    "....rr.....s....",
    "...DDD...sss....",
    "...DDD..sssss...",
    "................",
    "................",
  ],

  chop: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    ".rrrrrrrr..q....",
    "rrrrrrrrrr.qq...",
    ".rrwwwrr...q....",
    "..r.rrmm........",
    "..rr..m.........",
    ".DDD..m.........",
    ".DDD............",
    "................",
    "................",
  ],

  mine: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    ".rrrrrrrr.QQ....",
    "rrrrrrrrrr.Q....",
    ".rrwwwrr..QQ....",
    "..r.rrmm........",
    "..rr..m.........",
    ".DDD..m.........",
    ".DDD............",
    "................",
    "................",
  ],

  plant: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrr.......",
    "..rrrrrrrrr.....",
    "..rrwwwrrr......",
    "...r....rr......",
    "...rr...ro......",
    "..DDD..o........",
    "..DDD..o........",
    "................",
    "................",
  ],
};

// Per-personality colour substitutions. Pip (player): gold hair (y→o) + green tunic (r→G).
export const PERSONALITY_SUBS: Record<string, Record<string, string>> = {
  conservative: {},
  aggressive:   { y: "k", D: "k" },
  hoarder:      { y: "D", r: "y" },
  opportunist:  { y: "s", r: "S", D: "k" },
  pip:          { y: "o", r: "G" },
};

export function applyPersonalitySubs(
  pixels: readonly string[],
  subs: Record<string, string>,
): readonly string[] {
  if (Object.keys(subs).length === 0) return pixels;
  return pixels.map((row) =>
    row
      .split("")
      .map((ch) => subs[ch] ?? ch)
      .join(""),
  );
}

// Hat overlay: rows 0–3 only (clear of tool pixels at rows 7+). '.' = leave pixel; any other char = stamp.
// Each hat contrasts its personality's hair: conservative w/y, aggressive r/k, hoarder o/D, opportunist r+o/s, pip r/o.
export const PERSONALITY_HATS: Record<string, readonly string[]> = {
  conservative: [
    "................",
    "................",
    ".....wwwww......",
    "....w.....w.....",
  ],
  aggressive: [
    "................",
    ".....r.r.r......",
    ".....rrrrr......",
    "....r.....r.....",
  ],
  hoarder: [
    "................",
    "................",
    ".....ooooo......",
    "...ooooooooo....",
  ],
  opportunist: [
    "..........o.....",
    ".........ro.....",
    ".....rrrrr......",
    "....r.....r.....",
  ],
  pip: [
    "................",
    "......rrr.......",
    ".....rrrrr......",
    "....r.....r.....",
  ],
};

export function applyPersonalityHat(
  pixels: readonly string[],
  personality: string,
): readonly string[] {
  const hat = PERSONALITY_HATS[personality];
  if (!hat) return pixels;
  return pixels.map((row, y) => {
    const overlay = hat[y];
    if (!overlay) return row;
    let out = "";
    for (let x = 0; x < row.length; x++) {
      const stamp = overlay.charAt(x);
      out += stamp !== "" && stamp !== "." ? stamp : row.charAt(x);
    }
    return out;
  });
}

// Canonical farmer-frame transform: colour subs then hat. Applied uniformly across idle/walk/facing/action.
export function applyFarmerLook(
  pixels: readonly string[],
  personality: string,
  subs: Record<string, string>,
): readonly string[] {
  return applyPersonalityHat(applyPersonalitySubs(pixels, subs), personality);
}

// UP/SIDE facing variants (idle + 2 walk frames) generated per personality via PERSONALITY_SUBS.
// Renderer mirrors side frame for leftward movement (flipX). Authored in conservative chars.
export const FACING_TEMPLATES: Record<string, readonly string[]> = {
  up: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "...DDD.DDD......",
    "...DDD.DDD......",
    "................",
    "................",
  ],
  "up/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "..DDD...DDD.....",
    "..DDD...DDD.....",
    "................",
    "................",
  ],
  "up/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "....DDD.DDD.....",
    "....DDD.DDD.....",
    "................",
    "................",
  ],
  side: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "....r...r.......",
    "....DDDD........",
    "....DDDD........",
    "................",
    "................",
  ],
  "side/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "...rr...r.......",
    "..DDD....DD.....",
    "..DD......D.....",
    "................",
    "................",
  ],
  "side/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "....rr..r.......",
    ".....DDDD.......",
    ".....DD.DD......",
    "................",
    "................",
  ],
};

// Pip's down-facing frames (generated, not hand-authored). Up/side/action come from the shared loops.
export const PIP_DOWN_TEMPLATES: Record<string, readonly string[]> = {
  "": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "...DDD.DDD......",
    "...DDD.DDD......",
    "................",
    "................",
  ],
  "/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "..DDD...DDD.....",
    "..DDD...DDD.....",
    "................",
    "................",
  ],
  "/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "....DDD.DDD.....",
    "....DDD.DDD.....",
    "................",
    "................",
  ],
};

// NPC poses: standalone frames, not personality-substituted. Blacksmith: apron (D), hammer (m/Q). Carpenter: tunic (G/g), saw (q/m).
export const NPC_POSES: PixelRecipe[] = [
  {
    name: "npc/blacksmith/idle",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....DDDDD.......",
      "...DDDDDDD......",
      "...DDwwwDD......",
      "....D...D.......",
      "....D...D.......",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/carpenter/idle",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggg......",
      "...ggwwwgg......",
      "....g...g.......",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/blacksmith/hammer-a",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk....Q.",
      "....kkkkkkk..QQ.",
      "....kwwwwwk..m..",
      "....kw.w.kk..m..",
      "....kkwwwk..m...",
      "....DDDDD..m....",
      "...DDDDDDDm.....",
      "...DDwwwDD......",
      "....D...D.......",
      "....D...D.......",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/blacksmith/hammer-b",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....DDDDD.......",
      "...DDDDDDDm.....",
      "...DDwwwDDmm....",
      "....D...Dmm.Q...",
      "....D...D..QQ...",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/carpenter/saw-a",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggg.qqqq.",
      "...ggwwwggmqqqq.",
      "....g...g.m.....",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/carpenter/saw-b",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggqqqq...",
      "...ggwwwgmqqq...",
      "....g..ggm......",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "npc/barkeep/idle",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....w...w.......",
      "....w...w.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/barkeep/pour-a",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk..o...",
      "....rrrrr..oo...",
      "...rrrrrrroo....",
      "...rrwwwrr......",
      "....w...w.......",
      "....w...w.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "npc/barkeep/pour-b",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rrrrrrr.o....",
      "...rrwwwrroo....",
      "....w...woo.....",
      "....w...w.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/tavern",
    size: 16,
    pixels: [
      "................",
      "...rrrrrrrrrr...",
      "..rrrrrrrrrrrr..",
      "..MwwwwwwwwwwM..",
      "..MwDwwwwwDwwM..",
      "..MwwwwwwwwwwM..",
      "..MwDwwwwwDwwM..",
      "..MwwwoooowwwM..",
      "..MwwwoooowwwM..",
      "..MMMMooooMMMM..",
      ".....oooo.......",
      ".....oooo.......",
      "....MMMMMM......",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "structure/coop",
    size: 16,
    pixels: [
      "................",
      "....wwwwwwww....",
      "...wDDDDDDDDw...",
      "...DddddddddD...",
      "...DddkkdkddD...",
      "...Ddd..d.ddD...",
      "...DdddddddD....",
      "...DyyyyyyDD....",
      "...DyyyyyyyyD...",
      "...DDDDDDDDD....",
      ".....DD..DD.....",
      ".....DD..DD.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/barn",
    size: 16,
    pixels: [
      "................",
      "....rrrrrrrr....",
      "...rrrrrrrrrr...",
      "...rDDDDDDDDr...",
      "...rDwwwwwwDr...",
      "...rDwkwwkwDr...",
      "...rDwwwwwwDr...",
      "...rDDDDDDDDr...",
      "...rWWWWWWWrr...",
      "...rrrrrrrrrr...",
      ".....DD..DD.....",
      ".....DD..DD.....",
      ".....DD..DD.....",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "structure/greenhouse",
    size: 16,
    pixels: [
      ".......SS.......",
      "......SssS......",
      ".....SssssS.....",
      "....SssssssS....",
      "...SssggggssS...",
      "..SssgGGggssS...",
      "..SsssgggsssS...",
      "..SssSsssSssS...",
      "..SsssssssssS...",
      "..SssSsssSssS...",
      "..SssssssssssS..",
      "..SwwwwDDwwwwS..",
      "..SwwwwDdwwwwS..",
      "..SwwwwDdwwwwS..",
      "..SSSSSDdSSSSS..",
      "...kkkkkkkkk....",
    ],
  },
  {
    name: "tile/greenhouse-floor",
    size: 16,
    pixels: [
      "swwwwwwwwwwwwwws",
      "wDddddddddddddDw",
      "wdDDDDDDDDDDDDdw",
      "wdDddddddddddDdw",
      "wdDdDDDDDDDDdDdw",
      "wdDdDddddddDdDdw",
      "wdDdDdDDDDdDdDdw",
      "wdDdDdDddDdDdDdw",
      "wdDdDdDddDdDdDdw",
      "wdDdDdDDDDdDdDdw",
      "wdDdDddddddDdDdw",
      "wdDdDDDDDDDDdDdw",
      "wdDddddddddddDdw",
      "wdDDDDDDDDDDDDdw",
      "wDddddddddddddDw",
      "swwwwwwwwwwwwwws",
    ],
  },

  {
    name: "structure/fruit-tree-sapling",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......m........",
      ".......m........",
      "......mmm.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/fruit-tree-growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....lLlll......",
      "....lllllll.....",
      ".....lLlll......",
      "......lll.......",
      ".......m........",
      "......mmm.......",
      ".....mmmmm......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/fruit-tree-mature",
    size: 16,
    pixels: [
      "................",
      "......lll.......",
      ".....lLlll......",
      "....llolooll....",
      "...lllolollll...",
      "....llolooll....",
      ".....lololl.....",
      "......lll.......",
      "......mmm.......",
      ".....mmmmm......",
      "......mmm.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "animal/chicken",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......yyy.......",
      ".....ywwwy......",
      "....ywwwwwy.....",
      "....ywwwkwy.....",
      "....ywwwwwy.....",
      ".....ywwwy......",
      "......oyyy......",
      ".......yy.......",
      ".......yy.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "animal/cow",
    size: 16,
    pixels: [
      "................",
      "................",
      "....wwwwwwww....",
      "...wwwwkwwwww...",
      "...wwwkkkwwww...",
      "...wwwwwwwwww...",
      "...wwwwwwwwww...",
      "...wwwwkwwwww...",
      "....wwwwwwww....",
      ".....ww..ww.....",
      ".....ww..ww.....",
      ".....DD..DD.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "animal/sheep",
    size: 16,
    pixels: [
      "................",
      "................",
      "....qqqqqqqq....",
      "...qqQqQqQqqq...",
      "...qqqqqqqqkq...",
      "...qQqQqQqkkq...",
      "...qqqqqqqqkq...",
      "...qqQqQqQqqq...",
      "....qqqqqqqq....",
      ".....qq..qq.....",
      ".....qq..qq.....",
      ".....DD..DD.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "product/egg",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....kkkkk......",
      "....kwwwwwk.....",
      "....kwwwwwk.....",
      "....kwwwwwk.....",
      "....kwwwwwk.....",
      "....kTwwwwk.....",
      ".....kkkkk......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "product/milk",
    size: 16,
    pixels: [
      "................",
      "................",
      "......kkk.......",
      ".....kssk.......",
      "....kwwwwk......",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "product/wool",
    size: 16,
    pixels: [
      "................",
      "................",
      "....kkkkkk......",
      "...kqQqQqQk.....",
      "...kQqQqQqk.....",
      "...kqQqQqQk.....",
      "...kQqQqQqk.....",
      "...kqQqQqQk.....",
      "....kkkkkk......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "fruit/apple",
    size: 16,
    pixels: [
      "................",
      "........l.......",
      "......kkkk......",
      ".....krrrrk.....",
      "....krrrrrrk....",
      "....krrrrrrk....",
      "....krrrrrrk....",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......kkkk......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "fruit/cherry",
    size: 16,
    pixels: [
      "................",
      "................",
      "........ll......",
      "......ll.l......",
      ".....l..........",
      "....kk....kk....",
      "...krrk..krrk...",
      "...krrk..krrk...",
      "....kk....kk....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "npc/dockmaster/idle",
    size: 16,
    pixels: [
      "................",
      ".....MMMMM......",
      "....MMMMMMM.....",
      "....MwwwwwM.....",
      "....Mw.w.MM.....",
      "....MMwwwM......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },

  {
    name: "structure/dock",
    size: 16,
    pixels: [
      "vvvMMMMMMMMMvvvv",
      "vvvMdddddddMvvvv",
      "vvvMdDdDdDdMvvvv",
      "vvvMdddddddMvvvv",
      "vvvMdDdDdDdMvvvv",
      "vvvMdddddddMvvvv",
      "vvvMdDdDdDdMvvvv",
      "vvvMdddddddMvvvv",
      "vvvMMMMMMMMmvvvv",
      "vvvv.m...m.vvvvv",
      "vvvv.m...m.vvvvv",
      "vvvv.m...m.vvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
    ],
  },

  {
    name: "structure/cargo-ship",
    size: 16,
    pixels: [
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvDDDDDDDDvvvv",
      "vvvDdddddddddvvv",
      "vvDddwwwwwwdddvv",
      "vvDddwwmwwwdddvv",
      "vvDddwwmwwwdddvv",
      "vvDddDDmDDddddvv",
      "vvDdddddmddddvvv",
      "vvvDddddmDDdvvvv",
      "vvvvDdddmddvvvvv",
      "vvvvvDDDMDDvvvvv",
      "vvvvvvvMvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
      "vvvvvvvvvvvvvvvv",
    ],
  },
];
