import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "structure/big-tree-blossom",
  size: 48,
  width: 48,
  height: 64,
  pixels: [
    "................................................",
    "....................kkkkk.......................",
    "................kkkkkGPPGPkkk...................",
    ".............kkkGGGGGGPGGPGPGkk.................",
    "...........kkGGGGgGGGGGGGGPGGGGkk...............",
    ".........kkGGGggGGPPPGPGPPGnGGGGGkk.............",
    "........kGGGgPgwGPGPGGPPlPGPwGGGGGGk............",
    ".......kwPGPggGGGGGGGGGGGlPGGGPPGGGGkk..........",
    "......kGGPGPgPGGGPGwPPGGGGPGGwGGGGPGGPk.........",
    ".....kGGGGPGnwGGGnPGPPGGGGGGGGGGGGGGGGGk........",
    "....kGPGGPGGGGGPlGGGGGGGGGGGPnGPGPGGPGGGk.......",
    "...kGGGGPGGGwGPPlGGGPGPGGPGGGGGGGGGGGGGGGk......",
    "...kGGGGGwnGPGnGGGGwGPGGGPGGGGPGGGPPGGGPGk......",
    "..kGGGPPGPGGGGGPGGGwPGGGGGGGGGwGPGGGPPGGGGk.....",
    "..kGGgggGGGGPPPGGPGGGGGGGGGGGPGPGGwGPGGGPPk.....",
    "..kGGggPPGwGGGGPGGPGGlGGGGGPGGwGGGGGGPPGGGk.....",
    ".kGGGGGGGPGGGGGPPGGGGGlPGGGGGGGGGGGGGGGGGGGk....",
    ".kwPPGGGwGGGGGPPGGGPGGGPGGPGGGGGPnGPPGGGGGwk....",
    ".kGGGGGGGPlGGGGGPGPPGPGPGGwGGGGGGGGGGGGPGGGk....",
    ".kwGGGwGGPlnGGGPGGPGGPGGGGGGGGGPGGPggGPGGGPk....",
    ".kGPGPPGGPGGGGGGGnPwGGGPGPGPnGGGPPggPGGGGPGk....",
    "..kGGGPGGGGGPGGnPPGPGGGGGnGGGGGGGGPPgGGGGPk.....",
    "..kGPPGPPGGnGGGGGPGPGGPGGGGnGGGGGPGGnGGPGGk.....",
    "...kGGPGGGPGGGGPPPGGGGGGGGGGGGGPGGGGGPGGGk......",
    "...kknPnGPGPGGnPPPGGGGGGGGGGGGGGGPGGGGGGkk......",
    "....kkGGGGGPnGGGGGGGGGPGGGGGGPPGGGGPPPGkk.......",
    ".....kktPGGPPGGGGPGGGGGGGGGwGPGGGPPGtkk.........",
    "......kktGGGGGPttGGPGPGGGGGGttGGGGtkk...........",
    ".......kkttGGGPttGPGPPGGGGGGttGGttkk............",
    ".........kkttGGttGwGGmMGGPGttttkk...............",
    "...........kkttttPGGPmMGGGttkk..................",
    "..............kkkttnGmMGttkkk...................",
    "..................kkkmMkkk......................",
    ".....................mMD........................",
    "....................dmMD........................",
    "....................dmMDd.......................",
    "...................DdmMDd.......................",
    "...................DdmMMd.......................",
    "...................DdmMMd.......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    ".................DdddmMMddd.....................",
    ".................DdddmMMddd.....................",
    ".................DddmmMMMddd....................",
    "................DdddmmMMMddd....................",
    "................DddmmMMMMddd....................",
    "...............DdddmmMMMMdddd...................",
    "...............DddmmMMMMMdddd...................",
    "..............DdddmmMMMMMdddd...................",
    "..............DddmmMMMMMMdddd...................",
    ".............DdddmmMMMMMMddddd..................",
    ".............DddmmMMMMMMMddddd..................",
    "............DdddmmMMMMMMMdddddd.................",
    "...........DddmmMMMMMMMMMddddddd................",
    "..........DdddmmMMMMMMMMMddddddd................",
    ".........DddmmmMMMMMMMMMMMdddddddd..............",
    "........DddmmmMMMMMMMMMMMMMddddddd..............",
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkk..............",
    "......kGGGGGPGPGGGGGGGGGGnwPGPGGGGk.............",
    ".....kGGGGGGGGGGGPGGPPnGGGGGwGGGGGwk............",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........",
    "................................................",
    "................................................",
  ],
};

export default recipe;
