import { type PixelRecipe } from "../../types";

// Autumn variant of the big tree — IDENTICAL trunk+canopy silhouette to big-tree.ts,
// foliage shifted to autumn tones (a gold base, A orange light, f flame accents, t deep
// shade). A few stray f/A specks fall around the trunk as drifting leaves. Same outline
// so the season swap reads as the same tree turning.
const recipe: PixelRecipe = {
  name: "structure/big-tree-autumn",
  size: 48,
  width: 48,
  height: 64,
  pixels: [
    "................................................",
    "....................kkkkk.......................",
    "................kkkkkaaaaakkk...................",
    ".............kkkaaaaaaaaaaaaakk.................",
    "...........kkaaaaAaaaaaaaaaaaaakk...............",
    ".........kkaaaAAaaaaaaaaaaaaaaaaakk.............",
    "........kaaaAAAaaaaaaaaafaaaaaaaaaak............",
    ".......kaaaAAAaaaaaaaaaaafaaaaaaaaaakk..........",
    "......kaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaak.........",
    ".....kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak........",
    "....kaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaaaaak.......",
    "...kaaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaaaaaak......",
    "...kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak......",
    "..kaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak.....",
    "..kaaAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak.....",
    "..kaaAAAaaaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaak.....",
    ".kaaaaaaaaaaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaak....",
    ".kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak....",
    ".kaaaaaaaafaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak....",
    ".kaaaaaaaafaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaak....",
    ".kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAaaaaaak....",
    "..kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAaaaaak.....",
    "..kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak.....",
    "...kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak......",
    "...kkaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaakk......",
    "....kkaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaakk.......",
    ".....kktaaaaaaaaaaaaaaaaaaaaaaaaaaaatkk.........",
    "......kktaaaaaattaaaaaaaaaaattaaaatkk...........",
    ".......kkttaaaattaaaaaaaaaaattaattkk............",
    ".........kkttaattaaaamMaaaattttkk...............",
    "........f..kkttttaaaamMaaattkk....A.............",
    "...........kkkttaamMattkkk......................",
    ".....f............kkkmMkkk...f..................",
    ".....................mMD........A...............",
    "....................dmMD........................",
    "....................dmMDd.......................",
    "...................DdmMDd.......................",
    "...................DdmMMd.......................",
    "...................DdmMMd.......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    ".................DdddmMMddd.....................",
    ".................DdddmMMddd.....................",
    ".................DddmmMMMddd....................",
    "................DdddmmMMMddd....................",
    "................DddmmMMMMddd....................",
    "...............DdddmmMMMMdddd...................",
    "...............DddmmMMMMMdddd...................",
    "..............DdddmmMMMMMdddd...................",
    "..............DddmmMMMMMMdddd...................",
    ".............DdddmmMMMMMMddddd..................",
    ".............DddmmMMMMMMMddddd..................",
    "............DdddmmMMMMMMMdddddd.................",
    "...........DddmmMMMMMMMMMddddddd................",
    "..........DdddmmMMMMMMMMMddddddd................",
    ".........DddmmmMMMMMMMMMMMdddddddd..............",
    "........DddmmmMMMMMMMMMMMMMddddddd..............",
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkk..............",
    "......kaaaaaaaaaaaaaaaaaaaaaaaaaaak.............",
    ".....kaaaaaaaaaaaaaaaaaaaaaaaaaaaaak............",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........",
    "................................................",
    "................................................",
  ],
};

export default recipe;
