import { type PixelRecipe } from "../../types";

// Winter variant of the big tree — SAME thick trunk + buttressed base (rows below the
// crown are pixel-identical to big-tree.ts), but the canopy is stripped to bare branches
// (m/M trunk dark, D/d wood) fanning up from the trunk top, with snow flecks (n) caught on
// the limbs. Reads as the same tree gone dormant.
const recipe: PixelRecipe = {
  name: "structure/big-tree-bare",
  size: 48,
  width: 48,
  height: 64,
  pixels: [
    "................................................",
    "......n.............n..............n............",
    ".......D.........D..D.........D.................",
    "........Dd......Dd..dD......dD..n...............",
    ".....n...Dd....Dd....dD....dD...................",
    ".......D..Dd..Dd......dD..dD..D.................",
    "........Dd..DdDd...n...dDdD..dD.....n...........",
    "....n....Dd..DDd........dDD..dD.................",
    "..........Dd..Dd..D..D..dD..dD..................",
    "...n.......Dd..DddD..DddD..dD...n...............",
    "......D.....Dd..Dd....dD..dD..D.................",
    ".......Dd....Dd..D....D..dD..dD.................",
    "....n...Dd....DddD....DddD..dD...n..............",
    ".........Dd....Dd......dD..dD...................",
    "...n......Dd....DddmmddD..dD..D.................",
    "....D......Dd....DdmMmdD..dD....n...............",
    ".....Dd.....Dd....mMMm..dD..D...................",
    "......Dd.....DddmmMMMMmmddD..dD.................",
    "...n...Dd.....DdmMMMMMMmdD..dD..n...............",
    "........Dd.....mMMMMMMMMm..dD...................",
    ".........DddmmMMMMMMMMMMMmmddD..................",
    "..........DdmMMMMMMMMMMMMMMmdD..n...............",
    "...n........mMMMMMMMMMMMMMMMMm..................",
    ".............mMMMMMMMMMMMMMMm...................",
    "..............mMMMMMmmMMMMMm....................",
    "...n...........mMMMm..mMMMm.....n...............",
    "................mMMm..mMMm......................",
    ".................mMm..mMm.......................",
    "..................mM..Mm........................",
    ".................n.mMmMm..n.....................",
    "...................mMmM.........................",
    "....................mMm.........................",
    "....................mMM.........................",
    ".....................mMD........................",
    "....................dmMD........................",
    "....................dmMDd.......................",
    "...................DdmMDd.......................",
    "...................DdmMMd.......................",
    "...................DdmMMd.......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    "..................DddmMMdd......................",
    ".................DdddmMMddd.....................",
    ".................DdddmMMddd.....................",
    ".................DddmmMMMddd....................",
    "................DdddmmMMMddd....................",
    "................DddmmMMMMddd....................",
    "...............DdddmmMMMMdddd...................",
    "...............DddmmMMMMMdddd...................",
    "..............DdddmmMMMMMdddd...................",
    "..............DddmmMMMMMMdddd...................",
    ".............DdddmmMMMMMMddddd..................",
    ".............DddmmMMMMMMMddddd..................",
    "............DdddmmMMMMMMMdddddd.................",
    "...........DddmmMMMMMMMMMddddddd................",
    "..........DdddmmMMMMMMMMMddddddd................",
    ".........DddmmmMMMMMMMMMMMdddddddd..............",
    "........DddmmmMMMMMMMMMMMMMddddddd..............",
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkk..............",
    "......kqqqqqqqqqqqqqqqqqqqqqqqqqqqk.............",
    ".....kqqnqqqqqnqqqqqqqqnqqqqqnqqqqqk............",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........",
    "................................................",
    "................................................",
  ],
};

export default recipe;
