import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/cottage-pip",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............xx...............",
      "..............Rrxx..............",
      ".............Rrrrxx.............",
      "............Rrrrrrxx............",
      "............Rrxrrxxx............",
      "...........Rrrrrrrrxx...........",
      "..........Rrrrrrrrrrxx..........",
      ".........Rrrxrrxrrxrrxx.........",
      "........Rrrrrrrkkrrrrrxx........",
      ".......Rrrrrrrkqqkrrrrrxx.......",
      ".......Rxrrxrrkqnkrrxrrxx.......",
      "......Rrrrrrrrkqqkrrrrrrxx......",
      ".....Rrrrrrrrrrkkrrrrrrrrxx.....",
      "....Rrxrrxrrxrrxrrxrrxrrxrxx....",
      "...Rrrrrrrrrrrrrrrrrrrrrrrrxx...",
      "..Rrrrrrrrrrrrrrrrrrrrrrrrrrxx..",
      "..Rrrxrrxrrxrrxrrxrrxrrxrrxrxx..",
      ".Rrrrrrrrrrrrrrrrrrrrrrrrrrrrxx.",
      "Rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxx",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
