import { type PixelRecipe } from "../../types";

// Brief 77: 3D farm cottage (hoarder / green) — gable roof [leaf g / grass G / deep l] over a cream wall with
// wood posts, lit windows + door. 32x48, 2 tiles wide, bottom-anchored (rises 3 tiles).
// Top-left light direction. Roof color keys the owner's personality (see ui/colors.ts).
const recipe: PixelRecipe = {
    name: "structure/cottage-hoarder",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............gg...............",
      "..............gggg..............",
      ".............gGGGll.............",
      "............gGGGGGll............",
      "............gGGGGGll............",
      "...........gGGGGGGGll...........",
      "..........gGGGGGGGGGll..........",
      ".........gGGGGGGGGGGGll.........",
      "........gGGGGGGGGGGGGGll........",
      ".......gGGGGGGGGGGGGGGGll.......",
      ".......gGGGGGGGGGGGGGGGll.......",
      "......gGGGGGGGGGGGGGGGGGll......",
      ".....gGGGGGGGGGGGGGGGGGGGll.....",
      "....gGGGGGGGGGGGGGGGGGGGGGll....",
      "...gGGGGGGGGGGGGGGGGGGGGGGGll...",
      "..gGGGGGGGGGGGGGGGGGGGGGGGGGll..",
      "..gGGGGGGGGGGGGGGGGGGGGGGGGGll..",
      ".gGGGGGGGGGGGGGGGGGGGGGGGGGGGll.",
      "gGGGGGGGGGGGGGGGGGGGGGGGGGGGGGll",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkwHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykwHDD..",
      "..DDhwkyoykwwwwwwwwwwkyoykwHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykwHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkkkkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdokwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
