import { type PixelRecipe } from "../../types";

// Brief 77: 3D farm cottage (conservative / sky-blue) — gable roof [skyBlue e / ocean v / deep V] over a cream wall with
// wood posts, lit windows + door. 32x48, 2 tiles wide, bottom-anchored (rises 3 tiles).
// Top-left light direction. Roof color keys the owner's personality (see ui/colors.ts).
const recipe: PixelRecipe = {
    name: "structure/cottage-conservative",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............ee...............",
      "..............eeee..............",
      ".............evvvVV.............",
      "............evvvvvVV............",
      "............evvvvvVV............",
      "...........evvvvvvvVV...........",
      "..........evvvvvvvvvVV..........",
      ".........evvvvvvvvvvvVV.........",
      "........evvvvvvvvvvvvvVV........",
      ".......evvvvvvvvvvvvvvvVV.......",
      ".......evvvvvvvvvvvvvvvVV.......",
      "......evvvvvvvvvvvvvvvvvVV......",
      ".....evvvvvvvvvvvvvvvvvvvVV.....",
      "....evvvvvvvvvvvvvvvvvvvvvVV....",
      "...evvvvvvvvvvvvvvvvvvvvvvvVV...",
      "..evvvvvvvvvvvvvvvvvvvvvvvvvVV..",
      "..evvvvvvvvvvvvvvvvvvvvvvvvvVV..",
      ".evvvvvvvvvvvvvvvvvvvvvvvvvvvVV.",
      "evvvvvvvvvvvvvvvvvvvvvvvvvvvvvVV",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DDhWWWWWWWWWWWWWWWWWWWWWWHDD..",
      "..DDhWWWWWWWWWWWWWWWWWWWWWWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkWHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykWHDD..",
      "..DDhwkyoykwwwwwwwwwwkyoykWHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykWHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkkkkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdokwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwWHDD..",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
