import { type PixelRecipe } from "../../types";

// Brief 77: 3D farm cottage (aggressive / orange) — gable roof [flame f / clay A / rust r] over a cream wall with
// wood posts, lit windows + door. 32x48, 2 tiles wide, bottom-anchored (rises 3 tiles).
// Top-left light direction. Roof color keys the owner's personality (see ui/colors.ts).
const recipe: PixelRecipe = {
    name: "structure/cottage-aggressive",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............ff...............",
      "..............ffff..............",
      ".............fAAArr.............",
      "............fAAAAArr............",
      "............fAAAAArr............",
      "...........fAAAAAAArr...........",
      "..........fAAAAAAAAArr..........",
      ".........fAAAAAAAAAAArr.........",
      "........fAAAAAAAAAAAAArr........",
      ".......fAAAAAAAAAAAAAAArr.......",
      ".......fAAAAAAAAAAAAAAArr.......",
      "......fAAAAAAAAAAAAAAAAArr......",
      ".....fAAAAAAAAAAAAAAAAAAArr.....",
      "....fAAAAAAAAAAAAAAAAAAAAArr....",
      "...fAAAAAAAAAAAAAAAAAAAAAAArr...",
      "..fAAAAAAAAAAAAAAAAAAAAAAAAArr..",
      "..fAAAAAAAAAAAAAAAAAAAAAAAAArr..",
      ".fAAAAAAAAAAAAAAAAAAAAAAAAAAArr.",
      "fAAAAAAAAAAAAAAAAAAAAAAAAAAAAArr",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkwHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykwHDD..",
      "..DDhwkyoykwwwwwwwwwwkyoykwHDD..",
      "..DDhwkyyykwwwwwwwwwwkyyykwHDD..",
      "..DDhwkkkkkwwwwwwwwwwkkkkkwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwwwwwwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkkkkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdokwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..DDhwwwwwwwwwkdDkwwwwwwwwwHDD..",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
