import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/cottage-conservative",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............VV...............",
      "..............evVV..............",
      ".............evvvVV.............",
      "............evvvvvVV............",
      "............evVvvVVV............",
      "...........evvvvvvvVV...........",
      "..........evvvvvvvvvVV..........",
      ".........evvVvvVvvVvvVV.........",
      "........evvvvvvkkvvvvvVV........",
      ".......evvvvvvkqqkvvvvvVV.......",
      ".......eVvvVvvkqnkvvVvvVV.......",
      "......evvvvvvvkqqkvvvvvvVV......",
      ".....evvvvvvvvvkkvvvvvvvvVV.....",
      "....evVvvVvvVvvVvvVvvVvvVvVV....",
      "...evvvvvvvvvvvvvvvvvvvvvvvVV...",
      "..evvvvvvvvvvvvvvvvvvvvvvvvvVV..",
      "..evvVvvVvvVvvVvvVvvVvvVvvVvVV..",
      ".evvvvvvvvvvvvvvvvvvvvvvvvvvvVV.",
      "evvvvvvvvvvvvvvvvvvvvvvvvvvvvvVV",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
