import { type PixelRecipe } from "../../types";

// Brief 83 item 3 (Stardew restyle) — hoarder / green — shingled gable roof (leaf g / grass G / deep l). 32x48, 2 tiles wide, rises 3, bottom-anchored.
// Same geometry as cottage-conservative (round gable window, warm log-plank walls with courses, two
// green-framed windows, paneled door + gold knob, tan porch lip); only the roof palette keys the
// personality. Generated row-validated (every row 32 wide). EDG32 only.
const recipe: PixelRecipe = {
    name: "structure/cottage-hoarder",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............ll...............",
      "..............gGll..............",
      ".............gGGGll.............",
      "............gGGGGGll............",
      "............gGlGGlll............",
      "...........gGGGGGGGll...........",
      "..........gGGGGGGGGGll..........",
      ".........gGGlGGlGGlGGll.........",
      "........gGGGGGGkkGGGGGll........",
      ".......gGGGGGGkqqkGGGGGll.......",
      ".......glGGlGGkqnkGGlGGll.......",
      "......gGGGGGGGkqqkGGGGGGll......",
      ".....gGGGGGGGGGkkGGGGGGGGll.....",
      "....gGlGGlGGlGGlGGlGGlGGlGll....",
      "...gGGGGGGGGGGGGGGGGGGGGGGGll...",
      "..gGGGGGGGGGGGGGGGGGGGGGGGGGll..",
      "..gGGlGGlGGlGGlGGlGGlGGlGGlGll..",
      ".gGGGGGGGGGGGGGGGGGGGGGGGGGGGll.",
      "gGGGGGGGGGGGGGGGGGGGGGGGGGGGGGll",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
