import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/cottage-aggressive",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............rr...............",
      "..............fArr..............",
      ".............fAAArr.............",
      "............fAAAAArr............",
      "............fArAArrr............",
      "...........fAAAAAAArr...........",
      "..........fAAAAAAAAArr..........",
      ".........fAArAArAArAArr.........",
      "........fAAAAAAkkAAAAArr........",
      ".......fAAAAAAkqqkAAAAArr.......",
      ".......frAArAAkqnkAArAArr.......",
      "......fAAAAAAAkqqkAAAAAArr......",
      ".....fAAAAAAAAAkkAAAAAAAArr.....",
      "....fArAArAArAArAArAArAArArr....",
      "...fAAAAAAAAAAAAAAAAAAAAAAArr...",
      "..fAAAAAAAAAAAAAAAAAAAAAAAAArr..",
      "..fAArAArAArAArAArAArAArAArArr..",
      ".fAAAAAAAAAAAAAAAAAAAAAAAAAAArr.",
      "fAAAAAAAAAAAAAAAAAAAAAAAAAAAAArr",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
