import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
    name: "structure/forge-house",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "..........rrrr..................",
      "..........rkkr..................",
      "..........rkkr..................",
      "..........rrrr..................",
      ".........SrQQs..................",
      ".........srQQsQ.................",
      "........sSrQQssQ................",
      ".......sSSrQQsSSQ...............",
      "......sSSsrQQsSsSQ..............",
      ".....sSSsSrQQssSSsQ.............",
      "....sSSsSSrQQsSSsSSQ............",
      "...sSSsSSsrQQsSsSSsSQ...........",
      "..sSSsSSsSrQQssSSsSSsQ..........",
      ".sSSsSSsSSrQQsSSsSSsSSQ.........",
      "kkkkkkkkkkkkkkkkkkkkkkkk........",
      "DhddddddddddddddddddddHD........",
      "DhddddddddddddddddddddHD........",
      "DhDDDDDDDDDDDDDDDDDDDDHD........",
      "DhddllllllllddddddddddHD........",
      "DhddlqqqqqqlddddddddddHD........",
      "DhddlqoyyoqlddddddddddHD........",
      "DhDDlqqqqqqlDDDDDDDDDDHD........",
      "DhddlqoyyoqlddddddddddHD........",
      "DhddlqqqqqqlddddddddddHD........",
      "DhddllllllllddddddddddHD........",
      "DhddddddddddddddddddddHD........",
      "DhddddddddddddddddddddHD........",
      "DhDDDDDDDDDDDDDDDDDDDDHD........",
      "DhddddddddddddddddddddHD........",
      "DhddddddddddddddddddddHD........",
      "DhddddddddddddddddddddHD........",
      "DhDDDDDDDDDDDDDDDDDDDDHD........",
      "DhdddddddDqqqqDdddddddHD........",
      "DhdddddddDqqqqDdddddddHD........",
      "DhdddddddDqqqqDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddodDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DhdddddddDddddDdddddddHD........",
      "DDDDDDDDDDDDDDDDDDDDDDDD........",
      "WWWWWWWWWWWWWWWWWWWWWWWW........",
      "WWWWWWWWWWWWWWWWWWWWWWWW........",
      "kkkkkkkkkkkkkkkkkkkkkkkk........",
      "................................",
    ],
};

export default recipe;
