import { type PixelRecipe } from "../../types";

// Brief 87 restyle — Stardew cottage vocabulary. Pip's plain farmhouse; 32×48, 2 tiles wide,
// rises 3, bottom-anchored. Shingled gable roof in warm straw/hay palette (W tan / h warm highlight /
// H wicker shadow), same gable-window geometry as the personality cottages (round kqqk/kqnk),
// warm log-plank walls (d / D / h lit-left / H right), two green-framed windows with warm glow,
// a paneled door with upper light + gold knob, and a tan porch lip.
// Neutral "plain" roof distinguishes home from the personality-keyed cottage variants.
// EDG32 only. Generated row-validated (every row is 32 wide).
const recipe: PixelRecipe = {
    name: "structure/home",
    size: 32,
    width: 32,
    height: 48,
    pixels: [
      "...............HH...............",
      "..............WhHH..............",
      ".............WwwwHH.............",
      "............WwwwwwHH............",
      "............WwhwwHHH............",
      "...........WwwwwwwwHH...........",
      "..........WwwwwwwwwwHH..........",
      ".........WwwhwwhwwhwwHH.........",
      "........WwwwwwwkkwwwwwHH........",
      ".......WwwwwwwkqqkwwwwwHH.......",
      ".......WhwwhwwkqnkwwhwwHH.......",
      "......WwwwwwwwkqqkwwwwwwHH......",
      ".....WwwwwwwwwwkkwwwwwwwwHH.....",
      "....WwhwwhwwhwwhwwhwwhwwhwHH....",
      "...WwwwwwwwwwwwwwwwwwwwwwwwHH...",
      "..WwwwwwwwwwwwwwwwwwwwwwwwwwHH..",
      "..WwwhwwhwwhwwhwwhwwhwwhwwhwHH..",
      ".WwwwwwwwwwwwwwwwwwwwwwwwwwwwHH.",
      "WwwwwwwwwwwwwwwwwwwwwwwwwwwwwwHH",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddlqqqlddddddddddlqqqlddHD..",
      "..DhddlqyqlddddddddddlqyqlddHD..",
      "..DhDDlqqqlDDDDDDDDDDlqqqlDDHD..",
      "..DhddlllllddddddddddlllllddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhddddddddddddddddddddddddHD..",
      "..DhDDDDDDDDDDDDDDDDDDDDDDDDHD..",
      "..DhdddddddddDDDDDDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhdddddddddDqqqqDdddddddddHD..",
      "..DhDDDDDDDDDDddddDDDDDDDDDDHD..",
      "..DhdddddddddDdddoDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DhdddddddddDddddDdddddddddHD..",
      "..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      ".WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ],
};

export default recipe;
