import { type PixelRecipe } from "../../types";

// Brief 77: 3D weather-station — hipped roof (lit ridge s / body S / shadow N) over a
// tall stone front wall (q/Q/N) with lit windows + central door. 48x48, 3x3 tiles,
// bottom-anchored so it stands up off the island. Top-left light direction.
const recipe: PixelRecipe = {
    name: "structure/weather-station",
    size: 32,
    width: 48,
    height: 48,
    pixels: [
      "................................................",
      "................................................",
      "....................ssssssss....................",
      "...................ssSSSSSSNN...................",
      ".................ssSSSSSSSSSSNN.................",
      "................ssSSSSSSSSSSSSNN................",
      "...............ssSSSSSSSSSSSSSSNN...............",
      ".............ssSSSSSSSSSSSSSSSSSSNN.............",
      "............ssSSSSSSSSSSSSSSSSSSSSNN............",
      "...........ssSSSSSSSSSSSSSSSSSSSSSSNN...........",
      ".........ssSSSSSSSSSSSSSSSSSSSSSSSSSSNN.........",
      "........ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN........",
      ".......ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.......",
      ".....ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.....",
      "....ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN....",
      "...ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN...",
      ".ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN.",
      "ssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNN",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "...qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQkkkkkkQQQQQQQQQQQQQQQQQQkkkkkkQQQQNN...",
      "...qqQQQQkooookQQQQQQQQQQQQQQQQQQkooookQQQQNN...",
      "...qqQQQQkoyyokQQQQQQQQQQQQQQQQQQkoyyokQQQQNN...",
      "...qqQQQQkoyyokQQQQQQQQQQQQQQQQQQkoyyokQQQQNN...",
      "...qqQQQQkooookQQQQQQQQQQQQQQQQQQkooookQQQQNN...",
      "...qqQQQQkkkkkkQQQQQQQQQQQQQQQQQQkkkkkkQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkkkkkkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...qqQQQQQQQQQQQQQQQQkdDDdkQQQQQQQQQQQQQQQQNN...",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...",
    ],
};

export default recipe;
