import { type PixelRecipe } from "../../types";

const recipe: PixelRecipe = {
  name: "structure/weather-antenna",
  size: 16,
  width: 16,
  height: 64,
  pixels: [
    "......qqq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    ".qqqqqqQqqqqqq..",
    ".qQQQQQQQQQQQq..",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    ".....qqQqq......",
    ".....qQQQq......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "..qqqqqqQqqqq...",
    "..qQQQQQQQQQq...",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "....qqqqQqqq....",
    "....qQQQQQQq....",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "......qQq.......",
    "....qqQQQqq.....",
    "...qQQQQQQQq....",
    "..qQQQQQQQQQq...",
    ".qQQQQQQQQQQQq..",
    "QQQQQQQQQQQQQQQQ",
    "QQQQQQQQQQQQQQQQ",
    "kQQQQQQQQQQQQQQk",
    "................",
  ],
};

export default recipe;
