export interface PixelRecipe {
  name: string;
  size: number;
  pixels: readonly string[];
}

const SWATCH: Record<string, [number, number, number, number]> = {
  ".": [0, 0, 0, 0],
  G: [82, 137, 64, 255],
  g: [108, 165, 87, 255],
  D: [113, 76, 47, 255],
  d: [148, 102, 65, 255],
  S: [62, 90, 138, 255],
  s: [97, 134, 195, 255],
  k: [25, 22, 30, 255],
  w: [232, 226, 209, 255],
  r: [196, 64, 64, 255],
  l: [80, 150, 70, 255],
  L: [140, 200, 110, 255],
  p: [220, 130, 60, 255],
  y: [240, 210, 90, 255],
};

export function colorOf(ch: string): [number, number, number, number] {
  const c = SWATCH[ch];
  if (!c) throw new Error(`Unknown swatch char: ${ch}`);
  return c;
}

export const RECIPES: PixelRecipe[] = [
  {
    name: "tile/grass",
    size: 16,
    pixels: [
      "gggggggggggggggg",
      "gGgggGggggGgggGg",
      "ggggggggggggGggg",
      "gGggggGggggggggg",
      "gggggggggGgggGgg",
      "ggGggggggggggggg",
      "ggggGggggGgggggG",
      "gggggggggggggggg",
      "gGgggggGggggGggg",
      "ggggggggggggggGg",
      "gggGggggggGggggg",
      "ggggggGgggggggGg",
      "gGggggggggGggggg",
      "ggggggGggggggggg",
      "gggGggggGggGgggg",
      "gggggggggggggggg",
    ],
  },
  {
    name: "tile/dirt",
    size: 16,
    pixels: [
      "DDDDDDDDDDDDDDDD",
      "DdDDdDDDDdDDdDDD",
      "DDDDDDDdDDDDDDDD",
      "DdDDDDDDDDDDDDdD",
      "DDDDDDDDDDdDDDDD",
      "DDdDDDDdDDDDDDDD",
      "DDDDDdDDDDDDdDDD",
      "DDDDDDDDDDDDDDDd",
      "DdDDDDDDDDDDDDDD",
      "DDDDDDDdDDDDdDDD",
      "DDDDdDDDDDDdDDDD",
      "DdDDDDDDDdDDDDDD",
      "DDDDDDDDDDDDDDdD",
      "DDDdDDDDdDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
    ],
  },
  {
    name: "farmer/conservative",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      ".....lllll......",
      "......lll.......",
      "......rrr.......",
      ".....rrrrr......",
      "......rrr.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      "....lllllll.....",
      ".....llLll......",
      "......lll.......",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      ".....rrrrr......",
      "......rrr.......",
      ".......r........",
      "................",
      "................",
    ],
  },
];
