export interface PixelRecipe {
  name: string;
  size: number;
  pixels: readonly string[];
}

// Palette: Endesga-32 (EDG32) by Endesga — https://lospec.com/palette-list/endesga-32
// Every swatch below is one of the 32 EDG32 colors. The mapping is curated (not
// raw nearest-RGB) so grass stays green, the ocean stays blue with depth, and
// sand/wheat stay distinct (EDG32 has no teal, so a naive map muddied the grass).
const SWATCH: Record<string, [number, number, number, number]> = {
  ".": [0, 0, 0, 0],
  G: [62, 137, 72, 255],    // grass dark        #3e8948
  g: [99, 199, 77, 255],    // grass light       #63c74d
  D: [115, 62, 57, 255],    // wood dark         #733e39
  d: [184, 111, 80, 255],   // wood light        #b86f50
  S: [90, 105, 136, 255],   // structure blue    #5a6988
  s: [139, 155, 180, 255],  // structure blue lt #8b9bb4
  k: [24, 20, 37, 255],     // near-black        #181425
  w: [234, 212, 170, 255],  // cream / white     #ead4aa
  r: [190, 74, 47, 255],    // red / rust        #be4a2f
  l: [38, 92, 66, 255],     // leaf dark         #265c42
  L: [99, 199, 77, 255],    // leaf light        #63c74d
  W: [228, 166, 114, 255],  // tan / wheat       #e4a672
  m: [115, 62, 57, 255],    // trunk dark        #733e39
  M: [62, 39, 49, 255],     // trunk darker      #3e2731
  T: [234, 212, 170, 255],  // sand              #ead4aa
  c: [38, 92, 66, 255],     // grass base dark   #265c42
  C: [62, 137, 72, 255],    // grass base light  #3e8948
  q: [192, 203, 220, 255],  // stone light       #c0cbdc
  Q: [139, 155, 180, 255],  // stone dark        #8b9bb4
  o: [254, 174, 52, 255],   // gold              #feae34
  p: [215, 118, 67, 255],   // pumpkin           #d77643
  y: [254, 231, 97, 255],   // yellow            #fee761
  // Ocean shades for the out-of-region filler so the world reads as islands in
  // an ocean rather than a void beyond/between regions.
  v: [18, 78, 137, 255],    // ocean             #124e89
  V: [58, 68, 102, 255],    // ocean deep        #3a4466
  e: [0, 153, 219, 255],    // ocean foam        #0099db
};

export function colorOf(ch: string): [number, number, number, number] {
  const c = SWATCH[ch];
  if (!c) throw new Error(`Unknown swatch char: ${ch}`);
  return c;
}

export const RECIPES: PixelRecipe[] = [
  {
    // Shore — a foam + wet-sand band along the TOP edge of the tile. Placed on a
    // LAND tile that borders ocean and rotated (0/90/180/270) so the band faces
    // the adjacent water. Transparent elsewhere so the land tile shows through.
    // w=white foam, e=ocean highlight, T/W=wet sand.
    name: "tile/shore",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wewwewwwewwwewww",
      "TTwTTTwTTTTwTTTT",
      "TTTTTTTTTTTTTTTT",
      "WTTWTTTTWTTTWTTT",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Ocean — fills the gaps between/around the playable regions so the world
    // reads as islands in an ocean. Drawn under everything (it's non-walkable).
    // Gentle wave flecks (e) over two blues (v deeper between, V base) give the
    // water some life without animating. (Animated foam is a separate dynamic
    // overlay — see tile/foam-a/b/c.)
    name: "tile/ocean",
    size: 16,
    pixels: [
      "VVVVVVVVVVVVVVVV",
      "VVVVeVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVeVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVVVVeV",
      "VVVVVVVVVVVVVVVV",
      "eVVVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVeVVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVeVVVV",
      "VVeVVVVVVVVVVVVV",
      "VVVVVVVVVeVVVVVV",
      "VVVVeVVVVVVVVeVV",
      "VVVVVVVVVVVVVVVV",
    ],
  },
  {
    // Animated foam overlay, frame A. Drawn over ocean tiles by the main-thread
    // render loop, cycling A→B→C for a gentle shimmer. Transparent base (.) so
    // the static ocean shows through; e=highlight, w=white foam crest.
    name: "tile/foam-a",
    size: 16,
    pixels: [
      "................",
      "..e.........e...",
      "................",
      ".......w........",
      "................",
      "............e...",
      "...e............",
      "................",
      ".........w......",
      "................",
      "..e.........e...",
      "................",
      "......w.........",
      "................",
      ".............e..",
      "................",
    ],
  },
  {
    name: "tile/foam-b",
    size: 16,
    pixels: [
      "................",
      ".....e.......e..",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".............e..",
      "......w.........",
      "................",
      "...e............",
      "................",
      ".........e......",
      "....w...........",
      "................",
      "..e.......e.....",
      "................",
    ],
  },
  {
    name: "tile/foam-c",
    size: 16,
    pixels: [
      "................",
      "........e.....e.",
      "...w............",
      "................",
      "..........e.....",
      ".....e..........",
      "................",
      "............w...",
      "..e.............",
      "................",
      ".......e........",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".........e......",
    ],
  },
  {
    name: "tile/grass",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },
  {
    name: "tile/path",
    size: 16,
    pixels: [
      "TTTTTTTTTTTTTTTT",
      "TWTTWTTTWTTTWTTT",
      "TTTTTTTWTTTTTTTT",
      "TWTTTTTTTTTTTTWT",
      "TTTTTTTTTTWTTTTT",
      "TTWTTTTWTTTTTTTT",
      "TTTTTWTTTTTTWTTT",
      "TTTTTTTTTTTTTTTW",
      "TWTTTTTTTTTTTTTT",
      "TTTTTTTWTTTTWTTT",
      "TTTTWTTTTTTWTTTT",
      "TWTTTTTTTWTTTTTT",
      "TTTTTTTTTTTTTTWT",
      "TTTWTTTTWTTTTTTT",
      "TTTTTTTTTTTTTTTT",
      "TTTTTTTTTTTTTTTT",
    ],
  },
  {
    // Wooden plank bridge spanning a water gap between islands. Authored
    // HORIZONTAL (you walk left↔right across it): rail/support beams along the
    // top and bottom long edges (M = dark beam), a wood-plank deck (d = wood
    // light) with regular dark seams (D) every few columns, and a sliver of
    // ocean (v) peeking past each rail so it reads as crossing water. Vertical
    // bridges reuse this frame rotated 90° (see render-systems computeBridges).
    name: "tile/bridge-h",
    size: 16,
    pixels: [
      "vvvvvvvvvvvvvvvv",
      "MMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMM",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "dddDdddDdddDdddD",
      "MMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMM",
      "vvvvvvvvvvvvvvvv",
    ],
  },
  {
    name: "tile/fence-h",
    size: 16,
    pixels: [
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "mmmmmmmmmmmmmmmm",
      "WWWWWWWWWWWWWWWW",
      "mmmmmmmmmmmmmmmm",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
    ],
  },
  {
    name: "structure/market-wall",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWWM..",
      "..MWoooWoooWWM..",
      "..MWoooWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MWoWWWoooWWM..",
      "..MWoWWWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....DDDDDDDD....",
      "................",
    ],
  },
  {
    name: "structure/shopkeeper",
    size: 16,
    pixels: [
      "................",
      "......yyyy......",
      ".....yyyyyy.....",
      "....yyyyyyyy....",
      "...yyyyyyyyyy...",
      "..yyyyyyyyyyyy..",
      ".MMMMMMMMMMMMMM.",
      ".MWWoooWoooWWWM.",
      ".MWoWWWoWWoWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MWWWWWoWWWWWWM.",
      ".MWWWWoWoWWWWWM.",
      ".MWWWoWWWoWWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MMMMMMMMMMMMMM.",
      "....DDDDDDDD....",
    ],
  },
  {
    name: "tile/dirt",
    size: 16,
    pixels: [
      "DDDDDDDDDDDDDDDD",
      "DdDDdDDDDdDDdDDD",
      "DDDDDDDdDDDDDDDD",
      "DdDDDDDDDDDDDDdD",
      "DDDDDDDDDDdDDDDD",
      "DDdDDDDdDDDDDDDD",
      "DDDDDdDDDDDDdDDD",
      "DDDDDDDDDDDDDDDd",
      "DdDDDDDDDDDDDDDD",
      "DDDDDDDdDDDDdDDD",
      "DDDDdDDDDDDdDDDD",
      "DdDDDDDDDdDDDDDD",
      "DDDDDDDDDDDDDDdD",
      "DDDdDDDDdDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
    ],
  },
  {
    name: "farmer/conservative",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    // Speech-bubble icon rendered above farmers when a MEET fires.
    // White bubble with a dark outline and a yellow "!" exclamation mark inside.
    name: "indicator/meet",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      ".....lllll......",
      "......lll.......",
      "......rrr.......",
      ".....rrrrr......",
      "......rrr.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      "....lllllll.....",
      ".....llLll......",
      "......lll.......",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      ".....rrrrr......",
      "......rrr.......",
      ".......r........",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lLl.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "......yoy.......",
      ".....yyyyo......",
      "......oyo.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....l...l.......",
      "...lLl.lLl......",
      "....l...l.......",
      ".....l.l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......l........",
      "......lLl.......",
      ".....ppppp......",
      "....ppppppp.....",
      "....ppppppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Tile floors ─────────────────────────────────────────────────────────────
  {
    name: "tile/forge-floor",
    size: 16,
    pixels: [
      "QQQQQQQQqQQQQQQQ",
      "QqQQQQQQQQQQqQQQ",
      "QQQQqQQQQQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "qQQQQQQqQQQQQQQQ",
      "QQQQQQQQQQQQqQQQ",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQQqQQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQQqQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/market-floor",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
    ],
  },
  {
    name: "tile/quarry-floor",
    size: 16,
    pixels: [
      "QQQqQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQqQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQqQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQQQQqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    // Darkened plank floor: face is wood-light (d) over near-black bark grout
    // (M), instead of the old tan-over-wood-dark. The new floor reads clearly
    // darker so the tan/wood carpenter tools and props pop against it rather
    // than blending in.
    name: "tile/wood-plank",
    size: 16,
    pixels: [
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MMMMMMMMMMMMMMMM",
      "MddddddddddddddM",
      "MddddddddddddddM",
      "MddddddddddddddM",
    ],
  },
  {
    name: "tile/stone-floor",
    size: 16,
    pixels: [
      "QqQQQQqQQQQqQQQQ",
      "QQQQqQQQQQQQQQqQ",
      "qQQQQQQQqQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQqQQQ",
      "qQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQqQQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQqQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/ice-floor",
    size: 16,
    pixels: [
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
    ],
  },
  {
    name: "tile/mushroom-floor",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },

  // ── Structures ───────────────────────────────────────────────────────────────
  {
    name: "structure/blacksmith",
    size: 16,
    pixels: [
      "................",
      "..QQQQQQQQQQQQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQQQQQQQqqQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QQQQQQQQQQQQ..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....QQQQQQQQ....",
      "................",
    ],
  },
  {
    name: "structure/carpenter",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWwM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWWWWWWWWWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/fountain",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sSSSSSs.....",
      "....sSwwwSs.....",
      "....sSsssSSs....",
      ".....sSsSs......",
      "......sss.......",
      ".....sssss......",
      "....ssSSSSss....",
      "....sSSSSSSs....",
      "....sSSSSSSs....",
      "....ssSSSSss....",
      ".....ssssss.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/home",
    size: 16,
    pixels: [
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "...rrrrrrrrr....",
      "..MMMMMMMMMMMM..",
      "..MWWWoWWWoWWM..",
      "..MWWoWWWoWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/tree",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....CCCCC......",
      "....CCCCCCC.....",
      "...CCCCCCCCC....",
      "...CCCCCCCCC....",
      "....cCcCcCc.....",
      ".....CCCCC......",
      "......CCC.......",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/stone",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....QQQQQQ.....",
      "....QQqqqQQQ....",
      "....QqQQQqQQ....",
      "....QQqqqQQQ....",
      "....QQQQQQQQQ...",
      ".....QQQQQQQ....",
      "......QQQQ......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/auction-podium",
    size: 16,
    pixels: [
      "................",
      "................",
      "....TTTTTTTT....",
      "....TooooooT....",
      "....TooooooT....",
      "....TooooooT....",
      "....ToooWooT....",
      "....ToooWooT....",
      "....TTTTTTTT....",
      ".....TTTTTT.....",
      "......TTTT......",
      ".......TT.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/notice-board",
    size: 16,
    pixels: [
      "................",
      "................",
      "....mmmmmmmm....",
      "....mWWWWWWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWWWWWWm....",
      "....mmmmmmmm....",
      ".......mm.......",
      ".......mm.......",
      ".......mm.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mill",
    size: 16,
    pixels: [
      "................",
      "......yyy.......",
      ".....yyyyy......",
      "....MMMMMMM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MMMMMMM.....",
      ".....mm.mm......",
      ".....mm.mm......",
      ".....mm.mm......",
      "....MMMMMMM.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/well",
    size: 16,
    pixels: [
      "................",
      "...m........m...",
      "...m..ssss..m...",
      "...mmssSSssm....",
      "....msSSSssm....",
      "....msSSSssm....",
      "....mssssssm....",
      "....QQQQQQQQ....",
      "....QQQQQQQQ....",
      ".....QQQQQQ.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mushroom-marker",
    size: 16,
    pixels: [
      "................",
      "................",
      "......ppp.......",
      ".....ppppp......",
      "....ppwpppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      ".......l........",
      ".......l........",
      ".......l........",
      "......lll.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/ice-marker",
    size: 16,
    pixels: [
      "................",
      "......s.........",
      ".....sss........",
      "..s..sss..s.....",
      ".sss.sss.sss....",
      "sssssssssssss...",
      ".sss.sss.sss....",
      "..s..sss..s.....",
      ".....sss........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Workshop props — blacksmith forge ───────────────────────────────────────
  // Stationary decorations placed around the blacksmith. The NPC walks between
  // them and plays a pose (see ACTION_TEMPLATES hammer). The oven's fire is an
  // animated overlay (forge/fire-a/b/c) cycled by the render loop, drawn ABOVE
  // the static oven body so the flames flicker over a stable hearth.

  // Stone-and-brick oven/hearth with a dark mouth. The fire overlay sits in the
  // mouth (rows 6–9). Body uses stone (Q/q) + brick rust (r) + dark mouth (k).
  {
    name: "structure/forge-oven",
    size: 16,
    pixels: [
      "................",
      "....QQQQQQQQ....",
      "...QqqqqqqqqQ...",
      "...QqrqrqrqqQ...",
      "...QqqqqqqqqQ...",
      "...QkkkkkkkkQ...",
      "...Qkk....kkQ...",
      "...Qk......kQ...",
      "...Qk......kQ...",
      "...Qkk....kkQ...",
      "...QkkkkkkkkQ...",
      "...QqrqrqrqqQ...",
      "...QQQQQQQQQQ...",
      "....mm....mm....",
      "....MM....MM....",
      "................",
    ],
  },
  // Forge fire — frame A. Transparent base; drawn over forge-oven's mouth.
  // Flames: r (rust/base) → o (gold) → y (yellow tip). Cycled A→B→C.
  {
    name: "structure/forge-fire-a",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".....r..r.r.....",
      ".....ro.ror.....",
      ".....oyooyo.....",
      ".....royyor.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-fire-b",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......r........",
      ".....r.oo.r.....",
      ".....royyor.....",
      ".....oyyyyo.....",
      ".....royyor.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/forge-fire-c",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......r.r.......",
      ".....ror.r......",
      ".....oyoroo.....",
      ".....oyyyyo.....",
      ".....royoyr.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Anvil on a wooden stump. Steel face (q) + dark body (Q), horn to the left,
  // mounted on a brown stump (m/M). The NPC hammers facing this.
  {
    name: "structure/anvil",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "......qqqqq.....",
      "....qqQQQQQq....",
      "...QQQQQQQQQ....",
      "....QQQQQQQ.....",
      ".....QQQ........",
      ".....QQQQ.......",
      "....QQQQQQ......",
      "....mmmmmm......",
      "....mMMMMm......",
      "....mMMMMm......",
      "....MMMMMM......",
      "................",
    ],
  },
  // Quench tub — barrel of water for cooling hot metal. Wood staves (m/M) with
  // metal hoops (Q) and a water surface (v/e highlights).
  {
    name: "structure/quench-tub",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....QQQQQQQQ....",
      "....mvvevvvm....",
      "....mvvvvevm....",
      "....mevvvvvm....",
      "....QQQQQQQQ....",
      "....mMMMMMMm....",
      "....mMMMMMMm....",
      "....QQQQQQQQ....",
      "....mMMMMMMm....",
      "....mMMMMMMm....",
      "....MMMMMMMM....",
      "................",
      "................",
    ],
  },
  // Tool rack — hammers + tongs hung on a wooden wall board.
  {
    name: "structure/tool-rack",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWWM..",
      "..M.q..Q..q..M..",
      "..M.q..Q..Q..M..",
      "..M.m..m..m..M..",
      "..M.m..m..mm.M..",
      "..M.m..m..m..M..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Workshop props — carpenter ───────────────────────────────────────────────
  // Sturdy workbench with a plank top (W) on dark legs (M), a saw (q) resting on
  // it, and a couple of pegs.
  {
    name: "structure/workbench",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....qqqqqq.....",
      "....q......q....",
      "..WWWWWWWWWWWW..",
      "..WWWWWWWWWWWW..",
      "..MWWWWWWWWWWM..",
      "..M..........M..",
      "..M..........M..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "..MM........MM..",
      "................",
      "................",
    ],
  },
  // Sawhorse with a log being cut. X-legs (m) + crossbar, a log (d/D) on top.
  {
    name: "structure/sawhorse",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "....dddddddd....",
      "...dDdDdDdDdd...",
      "....dddddddd....",
      "..mmmmmmmmmmmm..",
      "...m.m....m.m...",
      "...m.m....m.m...",
      "..m...m..m...m..",
      "..m...m..m...m..",
      ".m....m..m....m.",
      ".m....m..m....m.",
      "................",
      "................",
      "................",
    ],
  },
  // Log pile — stacked round logs (end-grain).
  {
    name: "structure/log-pile",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....dddd.dddd...",
      "...dDmDddDmDd...",
      "...dDmDddDmDd...",
      "....dddd.dddd...",
      "..dddd.dddd.dd..",
      ".dDmDddDmDddDm..",
      ".dDmDddDmDddDm..",
      "..dddd.dddd.dd..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // Plank stack — sawn lumber stacked flat.
  {
    name: "structure/plank-stack",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "..WWWWWWWWWWWW..",
      "..MMMMMMMMMMMM..",
      "................",
      "................",
      "................",
    ],
  },

  // ── Farmer action poses (generated) ─────────────────────────────────────────
  // Action templates are authored once in conservative palette chars:
  //   head=y, shirt=r, legs=D, face=w, eyes=k.
  // Tool chars (m=brown handle, q=stone light, Q=stone dark, W=tan/wood,
  //             o=gold/seed, s=water blue-lt, e=water blue-hi) are NOT
  //   substituted, so they keep their colour across all personalities.
  //
  // Substitution maps applied per personality (in listed order):
  //   conservative: identity
  //   aggressive:   y→k, D→k
  //   hoarder:      y→D, r→y
  //   opportunist:  y→s, r→S, D→k
  //
  // The generator at the bottom of this file expands all 4 personalities ×
  // 7 actions (till/water/refill/chop/mine/plant/work) and pushes them in.
  // ──────────────────────────────────────────────────────────────────────────

  // ── Decorations ──────────────────────────────────────────────────────────────
  {
    name: "decoration/scarecrow",
    size: 16,
    pixels: [
      "................",
      "........m.......",
      ".......mmm......",
      "........m.......",
      "......yyyyy.....",
      ".......yyy......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/windmill",
    size: 16,
    pixels: [
      "................",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......Q........",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......m........",
      ".......m........",
      ".......m........",
      "......mmm.......",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/flower-bed",
    size: 16,
    pixels: [
      "................",
      "................",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....cccccccc....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/fence-art",
    size: 16,
    pixels: [
      "................",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWoWoWoWoWoWoWm.",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Debug ────────────────────────────────────────────────────────────────────
  {
    name: "debug/player",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rwwwwwr.....",
      "....rk.w.kr.....",
      "....rrwwwr......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
];

// ── Farmer action-pose generator ─────────────────────────────────────────────
// Each template is authored in conservative palette chars.
// Substitution maps correct the palette for every other personality.
// Tool chars (m q Q W o s e) are intentionally excluded from any substitution
// so they keep their original colour regardless of personality.

const ACTION_TEMPLATES: Record<string, readonly string[]> = {
  // Generic bent-over pose (was the single /work; now also the harvest fallback).
  work: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r.rrr.......",
    "....rr..........",
    "...DDD..........",
    "...DDD..........",
    "................",
    "................",
  ],

  // Hoe held at right side, blade angled down toward soil.
  // handle=m (brown), blade=Q (stone dark), no personality chars on tool.
  till: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrr.......",
    "..rrrrrrrrm.....",
    "..rrwwwrrmm.....",
    "...r....mm......",
    "...r...mm.......",
    "..DDD.Qm........",
    "..DDD..Q........",
    "................",
    "................",
  ],

  // Watering can held out front, tilted, with a few water droplets.
  // can body=Q (stone dark), spout=q (stone light), drops=s/e (water blues).
  water: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrrr......",
    "..rrrrrrrrr.....",
    "..rrwwwrrQQQ....",
    "...r....qQQ.....",
    "..DDD....s.s....",
    "..DDD.....s.....",
    "...........s....",
    "................",
    "................",
  ],

  // Crouched lower, dipping can toward water (refilling at well/fountain).
  // can=Q/q, water surface=s (structure blue light).
  refill: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrrr......",
    "...rrrrrrrrQQ...",
    "...rrwwwrqqQ....",
    "....r....qQ.....",
    "....rr.....s....",
    "...DDD...sss....",
    "...DDD..sssss...",
    "................",
    "................",
  ],

  // Mid-swing axe raised up to the right.
  // handle=m (brown), blade=q (stone light).
  chop: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    ".rrrrrrrr..q....",
    "rrrrrrrrrr.qq...",
    ".rrwwwrr...q....",
    "..r.rrmm........",
    "..rr..m.........",
    ".DDD..m.........",
    ".DDD............",
    "................",
    "................",
  ],

  // Mid-swing pickaxe raised up to the right.
  // handle=m (brown), pick head=Q (stone dark).
  mine: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    ".rrrrrrrr.QQ....",
    "rrrrrrrrrr.Q....",
    ".rrwwwrr..QQ....",
    "..r.rrmm........",
    "..rr..m.........",
    ".DDD..m.........",
    ".DDD............",
    "................",
    "................",
  ],

  // Bent forward, one arm reaching down, a few seed pixels on the soil.
  // seeds=o (gold).
  plant: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "...rrrrrr.......",
    "..rrrrrrrrr.....",
    "..rrwwwrrr......",
    "...r....rr......",
    "...rr...ro......",
    "..DDD..o........",
    "..DDD..o........",
    "................",
    "................",
  ],
};

// Per-personality char substitution maps.
// Each entry maps source chars to destination chars.
// Applied character-by-character to every pixel in the template.
const PERSONALITY_SUBS: Record<string, Record<string, string>> = {
  conservative: {},
  aggressive:   { y: "k", D: "k" },
  hoarder:      { y: "D", r: "y" },
  opportunist:  { y: "s", r: "S", D: "k" },
  // Pip — the player-controlled farmer. Gold hair (y→o) + green tunic (r→G) so
  // they read as visually distinct from all four AI farmers at a glance.
  pip:          { y: "o", r: "G" },
};

function applyPersonalitySubs(
  pixels: readonly string[],
  subs: Record<string, string>,
): readonly string[] {
  if (Object.keys(subs).length === 0) return pixels;
  return pixels.map((row) =>
    row
      .split("")
      .map((ch) => subs[ch] ?? ch)
      .join(""),
  );
}

for (const [action, template] of Object.entries(ACTION_TEMPLATES)) {
  for (const [personality, subs] of Object.entries(PERSONALITY_SUBS)) {
    RECIPES.push({
      name: `farmer/${personality}/${action}`,
      size: 16,
      pixels: applyPersonalitySubs(template, subs),
    });
  }
}

// ── Directional facing frames (3-way: down / up / side) ──────────────────────
// The existing `farmer/<p>` (+ /walk-a /walk-b) frames are the DOWN (front)
// facing. Here we author UP (back) and SIDE (profile, right-facing) variants for
// idle + 2 walk frames, then generate them for every personality via the same
// substitution maps. The renderer picks the facing from movement direction and
// mirrors the side frame horizontally for leftward movement (flipX).
//
// Frame names produced (per personality P):
//   farmer/P/up,   farmer/P/up/walk-a,   farmer/P/up/walk-b
//   farmer/P/side, farmer/P/side/walk-a, farmer/P/side/walk-b
// Authored in conservative chars (head/hair=y, face=w, eyes=k, shirt=r, legs=D).

const FACING_TEMPLATES: Record<string, readonly string[]> = {
  // UP — back of head: no face/eyes, just the hair block + back of shirt/legs.
  up: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "...DDD.DDD......",
    "...DDD.DDD......",
    "................",
    "................",
  ],
  "up/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "..DDD...DDD.....",
    "..DDD...DDD.....",
    "................",
    "................",
  ],
  "up/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyyy.....",
    "....yyyyyy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrr......",
    "....r...r.......",
    "....r...r.......",
    "....DDD.DDD.....",
    "....DDD.DDD.....",
    "................",
    "................",
  ],
  // SIDE — right-facing profile. One eye (k), face (w) toward +x, hair behind.
  // The renderer mirrors this (flipX) for leftward movement.
  side: [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "....r...r.......",
    "....DDDD........",
    "....DDDD........",
    "................",
    "................",
  ],
  "side/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "...rr...r.......",
    "..DDD....DD.....",
    "..DD......D.....",
    "................",
    "................",
  ],
  "side/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyyy....",
    "....ywwwwwy.....",
    "....ywwwwk.y....",
    "....yywwww......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrrrrrw......",
    "....r..rr.......",
    "....rr..r.......",
    ".....DDDD.......",
    ".....DD.DD......",
    "................",
    "................",
  ],
};

for (const [facing, template] of Object.entries(FACING_TEMPLATES)) {
  for (const [personality, subs] of Object.entries(PERSONALITY_SUBS)) {
    RECIPES.push({
      name: `farmer/${personality}/${facing}`,
      size: 16,
      pixels: applyPersonalitySubs(template, subs),
    });
  }
}

// ── Pip (player) down-facing base frames ─────────────────────────────────────
// The four AI farmers author their DOWN idle + walk frames explicitly above.
// Pip's are generated from the conservative down templates via the same per-
// personality substitution (pip = gold hair + green tunic). The up/side facing
// and all action poses were already generated for pip in the loops above (pip is
// a PERSONALITY_SUBS key); only these three front-facing frames remained.
const PIP_DOWN_TEMPLATES: Record<string, readonly string[]> = {
  "": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "...DDD.DDD......",
    "...DDD.DDD......",
    "................",
    "................",
  ],
  "/walk-a": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "..DDD...DDD.....",
    "..DDD...DDD.....",
    "................",
    "................",
  ],
  "/walk-b": [
    "................",
    "................",
    ".....yyyyy......",
    "....yyyyyyy.....",
    "....ywwwwwy.....",
    "....yk.w.ky.....",
    "....yywwwy......",
    "....rrrrr.......",
    "...rrrrrrr......",
    "...rrwwwrr......",
    "....r...r.......",
    "....r...r.......",
    "....DDD.DDD.....",
    "....DDD.DDD.....",
    "................",
    "................",
  ],
};

for (const [suffix, template] of Object.entries(PIP_DOWN_TEMPLATES)) {
  RECIPES.push({
    name: `farmer/pip${suffix}`,
    size: 16,
    pixels: applyPersonalitySubs(template, PERSONALITY_SUBS.pip!),
  });
}

// ── NPC work poses (blacksmith hammer, carpenter saw) ────────────────────────
// The blacksmith and carpenter NPCs cycle between their props playing these
// poses. Authored as standalone frames (not personality-substituted) — the NPCs
// have their own look. Two frames each for a simple up/down or push/pull swing.
//
// Blacksmith: apron (D), hammer with stone head (m handle, Q head).
// Carpenter:  green tunic (G/g), handsaw (q blade, m handle).
const NPC_POSES: PixelRecipe[] = [
  // Blacksmith idle — standing, hands at sides, no tool. Used while walking
  // between stations and while tending a station that has no swing pose (e.g.
  // the oven), so the NPC always reads as a person, never the building sprite.
  {
    name: "npc/blacksmith/idle",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....DDDDD.......",
      "...DDDDDDD......",
      "...DDwwwDD......",
      "....D...D.......",
      "....D...D.......",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  // Carpenter idle — standing, hands at sides, no tool (see blacksmith idle).
  {
    name: "npc/carpenter/idle",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggg......",
      "...ggwwwgg......",
      "....g...g.......",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  // Blacksmith hammer raised.
  {
    name: "npc/blacksmith/hammer-a",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk....Q.",
      "....kkkkkkk..QQ.",
      "....kwwwwwk..m..",
      "....kw.w.kk..m..",
      "....kkwwwk..m...",
      "....DDDDD..m....",
      "...DDDDDDDm.....",
      "...DDwwwDD......",
      "....D...D.......",
      "....D...D.......",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  // Blacksmith hammer struck down on the anvil.
  {
    name: "npc/blacksmith/hammer-b",
    size: 16,
    pixels: [
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kw.w.kk.....",
      "....kkwwwk......",
      "....DDDDD.......",
      "...DDDDDDDm.....",
      "...DDwwwDDmm....",
      "....D...Dmm.Q...",
      "....D...D..QQ...",
      "...mmm.mmm......",
      "...mmm.mmm......",
      "................",
      "................",
      "................",
    ],
  },
  // Carpenter saw pushed forward.
  {
    name: "npc/carpenter/saw-a",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggg.qqqq.",
      "...ggwwwggmqqqq.",
      "....g...g.m.....",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
  // Carpenter saw pulled back.
  {
    name: "npc/carpenter/saw-b",
    size: 16,
    pixels: [
      "................",
      ".....GGGGG......",
      "....GGGGGGG.....",
      "....GwwwwwG.....",
      "....Gw.w.GG.....",
      "....GGwwwG......",
      "....ggggg.......",
      "...ggggggqqqq...",
      "...ggwwwgmqqq...",
      "....g..ggm......",
      "....g...g.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
      "................",
    ],
  },
];
RECIPES.push(...NPC_POSES);
