export interface PixelRecipe {
  name: string;
  size: number;
  pixels: readonly string[];
}

const SWATCH: Record<string, [number, number, number, number]> = {
  ".": [0, 0, 0, 0],
  // Grass — shifted toward a cool teal/blue-green so the islands read as lush
  // tropical land against the ocean (the game is "islands in an ocean").
  G: [60, 150, 120, 255],  // teal-green accent (dark)
  g: [92, 185, 150, 255],  // teal-green accent (light)
  D: [113, 76, 47, 255],
  d: [148, 102, 65, 255],
  S: [62, 90, 138, 255],
  s: [97, 134, 195, 255],
  k: [25, 22, 30, 255],
  w: [232, 226, 209, 255],
  r: [196, 64, 64, 255],
  l: [80, 150, 70, 255],
  L: [140, 200, 110, 255],
  W: [183, 137, 78, 255],
  m: [120, 84, 47, 255],
  M: [70, 48, 26, 255],
  T: [200, 170, 110, 255],
  c: [48, 110, 96, 255],   // grass base (dark) — teal-green
  C: [70, 140, 118, 255],  // grass base (light) — teal-green
  q: [180, 180, 190, 255],
  Q: [140, 140, 150, 255],
  o: [232, 195, 80, 255],
  p: [220, 130, 60, 255],
  y: [240, 210, 90, 255],
  // Ocean shades for the out-of-region filler so the world reads as islands in
  // an ocean rather than a black/grass void beyond and between regions.
  v: [38, 92, 150, 255],   // ocean blue
  V: [30, 76, 132, 255],   // deeper ocean blue
  e: [78, 140, 190, 255],  // ocean highlight (foam/sparkle)
};

export function colorOf(ch: string): [number, number, number, number] {
  const c = SWATCH[ch];
  if (!c) throw new Error(`Unknown swatch char: ${ch}`);
  return c;
}

export const RECIPES: PixelRecipe[] = [
  {
    // Shore — a foam + wet-sand band along the TOP edge of the tile. Placed on a
    // LAND tile that borders ocean and rotated (0/90/180/270) so the band faces
    // the adjacent water. Transparent elsewhere so the land tile shows through.
    // w=white foam, e=ocean highlight, T/W=wet sand.
    name: "tile/shore",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wewwewwwewwwewww",
      "TTwTTTwTTTTwTTTT",
      "TTTTTTTTTTTTTTTT",
      "WTTWTTTTWTTTWTTT",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    // Ocean — fills the gaps between/around the playable regions so the world
    // reads as islands in an ocean. Drawn under everything (it's non-walkable).
    // Gentle wave flecks (e) over two blues (v deeper between, V base) give the
    // water some life without animating. (Animated foam is a separate dynamic
    // overlay — see tile/foam-a/b/c.)
    name: "tile/ocean",
    size: 16,
    pixels: [
      "VVVVVVVVVVVVVVVV",
      "VVVVeVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVeVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVVVVeV",
      "VVVVVVVVVVVVVVVV",
      "eVVVVVVVVeVVVVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVeVVVVVVVVeVVV",
      "VVVVVVVVVVVVVVVV",
      "VVVVVVeVVVVeVVVV",
      "VVeVVVVVVVVVVVVV",
      "VVVVVVVVVeVVVVVV",
      "VVVVeVVVVVVVVeVV",
      "VVVVVVVVVVVVVVVV",
    ],
  },
  {
    // Animated foam overlay, frame A. Drawn over ocean tiles by the main-thread
    // render loop, cycling A→B→C for a gentle shimmer. Transparent base (.) so
    // the static ocean shows through; e=highlight, w=white foam crest.
    name: "tile/foam-a",
    size: 16,
    pixels: [
      "................",
      "..e.........e...",
      "................",
      ".......w........",
      "................",
      "............e...",
      "...e............",
      "................",
      ".........w......",
      "................",
      "..e.........e...",
      "................",
      "......w.........",
      "................",
      ".............e..",
      "................",
    ],
  },
  {
    name: "tile/foam-b",
    size: 16,
    pixels: [
      "................",
      ".....e.......e..",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".............e..",
      "......w.........",
      "................",
      "...e............",
      "................",
      ".........e......",
      "....w...........",
      "................",
      "..e.......e.....",
      "................",
    ],
  },
  {
    name: "tile/foam-c",
    size: 16,
    pixels: [
      "................",
      "........e.....e.",
      "...w............",
      "................",
      "..........e.....",
      ".....e..........",
      "................",
      "............w...",
      "..e.............",
      "................",
      ".......e........",
      "................",
      "..........w.....",
      "....e...........",
      "................",
      ".........e......",
    ],
  },
  {
    name: "tile/grass",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },
  {
    name: "tile/path",
    size: 16,
    pixels: [
      "TTTTTTTTTTTTTTTT",
      "TWTTWTTTWTTTWTTT",
      "TTTTTTTWTTTTTTTT",
      "TWTTTTTTTTTTTTWT",
      "TTTTTTTTTTWTTTTT",
      "TTWTTTTWTTTTTTTT",
      "TTTTTWTTTTTTWTTT",
      "TTTTTTTTTTTTTTTW",
      "TWTTTTTTTTTTTTTT",
      "TTTTTTTWTTTTWTTT",
      "TTTTWTTTTTTWTTTT",
      "TWTTTTTTTWTTTTTT",
      "TTTTTTTTTTTTTTWT",
      "TTTWTTTTWTTTTTTT",
      "TTTTTTTTTTTTTTTT",
      "TTTTTTTTTTTTTTTT",
    ],
  },
  {
    name: "tile/fence-h",
    size: 16,
    pixels: [
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "mmmmmmmmmmmmmmmm",
      "WWWWWWWWWWWWWWWW",
      "mmmmmmmmmmmmmmmm",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "..m...m...m...m.",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
      "cccccccccccccccc",
    ],
  },
  {
    name: "structure/market-wall",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWWM..",
      "..MWoooWoooWWM..",
      "..MWoooWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MWoWWWoooWWM..",
      "..MWoWWWoooWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....DDDDDDDD....",
      "................",
    ],
  },
  {
    name: "structure/shopkeeper",
    size: 16,
    pixels: [
      "................",
      "......yyyy......",
      ".....yyyyyy.....",
      "....yyyyyyyy....",
      "...yyyyyyyyyy...",
      "..yyyyyyyyyyyy..",
      ".MMMMMMMMMMMMMM.",
      ".MWWoooWoooWWWM.",
      ".MWoWWWoWWoWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MWWWWWoWWWWWWM.",
      ".MWWWWoWoWWWWWM.",
      ".MWWWoWWWoWWWWM.",
      ".MWWWWWWWWWWWWM.",
      ".MMMMMMMMMMMMMM.",
      "....DDDDDDDD....",
    ],
  },
  {
    name: "tile/dirt",
    size: 16,
    pixels: [
      "DDDDDDDDDDDDDDDD",
      "DdDDdDDDDdDDdDDD",
      "DDDDDDDdDDDDDDDD",
      "DdDDDDDDDDDDDDdD",
      "DDDDDDDDDDdDDDDD",
      "DDdDDDDdDDDDDDDD",
      "DDDDDdDDDDDDdDDD",
      "DDDDDDDDDDDDDDDd",
      "DdDDDDDDDDDDDDDD",
      "DDDDDDDdDDDDdDDD",
      "DDDDdDDDDDDdDDDD",
      "DdDDDDDDDdDDDDDD",
      "DDDDDDDDDDDDDDdD",
      "DDDdDDDDdDDDDDDD",
      "DDDDDDDDDDDDDDDD",
      "DDDDDDDDDDDDDDDD",
    ],
  },
  {
    name: "farmer/conservative",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/conservative/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....kkkkk......",
      "....kkkkkkk.....",
      "....kwwwwwk.....",
      "....kk.w.kk.....",
      "....kkwwwk......",
      "....rrrrr.......",
      "...rkrrrkr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "..DDD...DDD.....",
      "..DDD...DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....DDDDD......",
      "....DDDDDDD.....",
      "....DwwwwwD.....",
      "....Dk.w.kD.....",
      "....DDwwwD......",
      "....yyyyy.......",
      "...yyyyyyy......",
      "...yywwwyy......",
      "....y...y.......",
      "....y...y.......",
      "....DDD.DDD.....",
      "....DDD.DDD.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "...kkk.kkk......",
      "...kkk.kkk......",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-a",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "..kkk...kkk.....",
      "..kkk...kkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/walk-b",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sssssss.....",
      "....swwwwws.....",
      "....sk.w.ks.....",
      "....sswwws......",
      "....SSSSS.......",
      "...SSSSSSS......",
      "...SSwwwSS......",
      "....S...S.......",
      "....S...S.......",
      "....kkk.kkk.....",
      "....kkk.kkk.....",
      "................",
      "................",
    ],
  },
  {
    // Speech-bubble icon rendered above farmers when a MEET fires.
    // White bubble with a dark outline and a yellow "!" exclamation mark inside.
    name: "indicator/meet",
    size: 16,
    pixels: [
      "................",
      "....kkkkkk......",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "...kwwowwwk.....",
      "...kwwwwwwk.....",
      "....kkkkkk......",
      ".....kk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      ".....lllll......",
      "......lll.......",
      "......rrr.......",
      ".....rrrrr......",
      "......rrr.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/radish/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "......lll.......",
      ".....llLll......",
      "....lllllll.....",
      ".....llLll......",
      "......lll.......",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rrrrrrr.....",
      ".....rrrrr......",
      "......rrr.......",
      ".......r........",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lLl.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/wheat/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "......yoy.......",
      ".....yyyyo......",
      "......oyo.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......lll.......",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/seed",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/growing",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      "................",
      "....l...l.......",
      "...lLl.lLl......",
      "....l...l.......",
      ".....l.l........",
      "......lll.......",
      ".......l........",
      ".......l........",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "crop/pumpkin/mature",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".......l........",
      "......lLl.......",
      ".....ppppp......",
      "....ppppppp.....",
      "....ppppppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      "......dkd.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Tile floors ─────────────────────────────────────────────────────────────
  {
    name: "tile/forge-floor",
    size: 16,
    pixels: [
      "QQQQQQQQqQQQQQQQ",
      "QqQQQQQQQQQQqQQQ",
      "QQQQqQQQQQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "qQQQQQQqQQQQQQQQ",
      "QQQQQQQQQQQQqQQQ",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQQqQQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQQqQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/market-floor",
    size: 16,
    pixels: [
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwwwwwwwwwwwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wTTTTwwwwTTTTwww",
      "wwwwwwwwwwwwwwww",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
      "wwwwTTTTwwwwTTTT",
    ],
  },
  {
    name: "tile/quarry-floor",
    size: 16,
    pixels: [
      "QQQqQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQqQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQqQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQQqQQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQQQQqQ",
      "QQQQQQQQQQQQQQQQ",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQQQQq",
      "QQQQQQQQQQQQQQQQ",
      "QQqQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/wood-plank",
    size: 16,
    pixels: [
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
      "mWWWWWWWWWWWWWWm",
    ],
  },
  {
    name: "tile/stone-floor",
    size: 16,
    pixels: [
      "QqQQQQqQQQQqQQQQ",
      "QQQQqQQQQQQQQQqQ",
      "qQQQQQQQqQQQQQQQ",
      "QQQQQQQQQQqQQQQq",
      "QQqQQQQQQQQQQQQQ",
      "QQQQQqQQQQQQqQQQ",
      "qQQQQQQQQQQQQQQQ",
      "QQQQQQQqQQQqQQQQ",
      "QQQQQQQQQQQQQQqQ",
      "qQQqQQQQQQQQQQQQ",
      "QQQQQQQQQqQQQQQQ",
      "QQQQQQQQQQQQQQQq",
      "QqQQQQQQQQQqQQQQ",
      "QQQQQQQQQQQQQQQQ",
      "QQQqQQQQQQQQqQQQ",
      "QQQQQQQQQQQQQQQQ",
    ],
  },
  {
    name: "tile/ice-floor",
    size: 16,
    pixels: [
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssSSSSSSSSSSSSSs",
      "ssssssssssssssss",
      "sSSSSSSSSSSSSSss",
      "sSSSSSSSSSSSSSss",
      "ssssssssssssssss",
    ],
  },
  {
    name: "tile/mushroom-floor",
    size: 16,
    pixels: [
      "cccCcccccccccccc",
      "cCcccCccccGcccGc",
      "cccccccccccCGccc",
      "cGcccccGcccccccc",
      "ccCccccccGcccCcc",
      "ccGcccccccccccCc",
      "ccccCcccCGccccGc",
      "ccccccccccccCccc",
      "cGcccccGcccCGccc",
      "ccccccccccccCcGc",
      "ccCcccccccGccccc",
      "ccccccGcccccccGc",
      "cGcccCcccccccccc",
      "ccccccGcccccCccc",
      "cccGcccccGcGcccc",
      "ccccccCccccccccc",
    ],
  },

  // ── Structures ───────────────────────────────────────────────────────────────
  {
    name: "structure/blacksmith",
    size: 16,
    pixels: [
      "................",
      "..QQQQQQQQQQQQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQrrQrrQqQQ..",
      "..QqQQQQQQQqqQ..",
      "..QqqqqqqqqqqQ..",
      "..QqQQQQQQQqqQ..",
      "..QQQQQQQQQQQQ..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....QQQQQQQQ....",
      "................",
    ],
  },
  {
    name: "structure/carpenter",
    size: 16,
    pixels: [
      "................",
      "..MMMMMMMMMMMM..",
      "..MWWWWWWWWWwM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmWWWmWWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWWWWWWWWWWM..",
      "..MWWWWWWWWWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/fountain",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....sssss......",
      "....sSSSSSs.....",
      "....sSwwwSs.....",
      "....sSsssSSs....",
      ".....sSsSs......",
      "......sss.......",
      ".....sssss......",
      "....ssSSSSss....",
      "....sSSSSSSs....",
      "....sSSSSSSs....",
      "....ssSSSSss....",
      ".....ssssss.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/home",
    size: 16,
    pixels: [
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "...rrrrrrrrr....",
      "..MMMMMMMMMMMM..",
      "..MWWWoWWWoWWM..",
      "..MWWoWWWoWWWM..",
      "..MWWWWWWWWwWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MWmmmWmmmWWM..",
      "..MMMMMMMMMMMM..",
      ".....mm..mm.....",
      ".....mm..mm.....",
      "....MMMMMMMM....",
      "................",
    ],
  },
  {
    name: "structure/tree",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....CCCCC......",
      "....CCCCCCC.....",
      "...CCCCCCCCC....",
      "...CCCCCCCCC....",
      "....cCcCcCc.....",
      ".....CCCCC......",
      "......CCC.......",
      ".......m........",
      ".......m........",
      ".......m........",
      ".......m........",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/stone",
    size: 16,
    pixels: [
      "................",
      "................",
      "................",
      ".....QQQQQQ.....",
      "....QQqqqQQQ....",
      "....QqQQQqQQ....",
      "....QQqqqQQQ....",
      "....QQQQQQQQQ...",
      ".....QQQQQQQ....",
      "......QQQQ......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/auction-podium",
    size: 16,
    pixels: [
      "................",
      "................",
      "....TTTTTTTT....",
      "....TooooooT....",
      "....TooooooT....",
      "....TooooooT....",
      "....ToooWooT....",
      "....ToooWooT....",
      "....TTTTTTTT....",
      ".....TTTTTT.....",
      "......TTTT......",
      ".......TT.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/notice-board",
    size: 16,
    pixels: [
      "................",
      "................",
      "....mmmmmmmm....",
      "....mWWWWWWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWTTTTWm....",
      "....mWWWWWWm....",
      "....mmmmmmmm....",
      ".......mm.......",
      ".......mm.......",
      ".......mm.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mill",
    size: 16,
    pixels: [
      "................",
      "......yyy.......",
      ".....yyyyy......",
      "....MMMMMMM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MWoWoWM.....",
      "....MWWWWwM.....",
      "....MMMMMMM.....",
      ".....mm.mm......",
      ".....mm.mm......",
      ".....mm.mm......",
      "....MMMMMMM.....",
      "................",
      "................",
    ],
  },
  {
    name: "structure/well",
    size: 16,
    pixels: [
      "................",
      "...m........m...",
      "...m..ssss..m...",
      "...mmssSSssm....",
      "....msSSSssm....",
      "....msSSSssm....",
      "....mssssssm....",
      "....QQQQQQQQ....",
      "....QQQQQQQQ....",
      ".....QQQQQQ.....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/mushroom-marker",
    size: 16,
    pixels: [
      "................",
      "................",
      "......ppp.......",
      ".....ppppp......",
      "....ppwpppp.....",
      "....ppppppp.....",
      ".....ppppp......",
      "......ppp.......",
      ".......l........",
      ".......l........",
      ".......l........",
      "......lll.......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "structure/ice-marker",
    size: 16,
    pixels: [
      "................",
      "......s.........",
      ".....sss........",
      "..s..sss..s.....",
      ".sss.sss.sss....",
      "sssssssssssss...",
      ".sss.sss.sss....",
      "..s..sss..s.....",
      ".....sss........",
      "......s.........",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Farmer work poses ────────────────────────────────────────────────────────
  {
    name: "farmer/conservative/work",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r.rrr.......",
      "....rr..........",
      "...DDD..........",
      "...DDD..........",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/aggressive/work",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r.rrr.......",
      "....rr..........",
      "...DDD..........",
      "...DDD..........",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/hoarder/work",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r.rrr.......",
      "....rr..........",
      "...DDD..........",
      "...DDD..........",
      "................",
      "................",
    ],
  },
  {
    name: "farmer/opportunist/work",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....yyyyy......",
      "....yyyyyyy.....",
      "....ywwwwwy.....",
      "....yk.w.ky.....",
      "....yywwwy......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r.rrr.......",
      "....rr..........",
      "...DDD..........",
      "...DDD..........",
      "................",
      "................",
    ],
  },

  // ── Decorations ──────────────────────────────────────────────────────────────
  {
    name: "decoration/scarecrow",
    size: 16,
    pixels: [
      "................",
      "........m.......",
      ".......mmm......",
      "........m.......",
      "......yyyyy.....",
      ".......yyy......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "........m.......",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/windmill",
    size: 16,
    pixels: [
      "................",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......Q........",
      "......QQQ.......",
      ".....QQQQQ......",
      ".....QQoQQ......",
      "......QQQ.......",
      ".......m........",
      ".......m........",
      ".......m........",
      "......mmm.......",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/flower-bed",
    size: 16,
    pixels: [
      "................",
      "................",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....rLrLrLrL....",
      "....LrLrLrLr....",
      "....cccccccc....",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "decoration/fence-art",
    size: 16,
    pixels: [
      "................",
      "mmmmmmmmmmmmmmmm",
      "mWWWWWWWWWWWWWWm",
      "mWoWoWoWoWoWoWm.",
      "mWWWWWWWWWWWWWWm",
      "mmmmmmmmmmmmmmmm",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // ── Debug ────────────────────────────────────────────────────────────────────
  {
    name: "debug/player",
    size: 16,
    pixels: [
      "................",
      "................",
      ".....rrrrr......",
      "....rrrrrrr.....",
      "....rwwwwwr.....",
      "....rk.w.kr.....",
      "....rrwwwr......",
      "....rrrrr.......",
      "...rrrrrrr......",
      "...rrwwwrr......",
      "....r...r.......",
      "....r...r.......",
      "...DDD.DDD......",
      "...DDD.DDD......",
      "................",
      "................",
    ],
  },
];
