export { HollowJobAssignmentSystem } from "./assignment-system";
export type { JobAssignmentSystemOptions } from "./assignment-system";
export {
  JOBS_ASSIGN_INTERVAL_TICKS,
  ASSIGNABLE_JOB_ROLES,
  ROLE_CRAFTER_MATERIAL_WEIGHT,
  ROLE_CRAFTER_CURIOSITY_WEIGHT,
  ROLE_TEACHER_CURIOSITY_WEIGHT,
  ROLE_TEACHER_SOCIABILITY_WEIGHT,
  ROLE_CARETAKER_LOYALTY_WEIGHT,
  ROLE_CARETAKER_SOCIABILITY_WEIGHT,
  JOBS_DEMAND_PERCAPITA_TARGET,
  JOBS_DEMAND_BIAS_WEIGHT,
  JOBS_PRODUCTION_SURPLUS_FRACTION,
  JOBS_FOOD_WORK_SESSION_TARGET,
  ROLE_SHARE_BIAS,
  ROLE_TEACH_BIAS,
  ROLE_TEACH_COMMUNITY_BONUS,
  ROLE_CARETAKER_BIAS,
  ROLE_CARETAKER_NEEDY_SELECTION_WEIGHT,
} from "./constants";
