/**
 * Building FRAME NAMES.
 *
 * The building ART itself is no longer authored here. Every `bld/<type>` frame —
 * all 21 base buildings, the mill's rotated-sail animation frames, and the four
 * dusk-lit `@lit` companions — is generated by the 3D-mesh pipeline
 * (`../mesh/`) and spliced into the atlas as `MESH_OVERRIDES`. The old ASCII
 * char-recipe forms (`iso-draw.ts`: cottage / postMill / fort / …) and the
 * `BUILDING_RECIPES` list they fed were deleted once the mesh set covered
 * everything, since nothing rendered them any more.
 *
 * What survives is the naming vocabulary shared by the renderer (`quads.ts`),
 * the recipe barrel (`index.ts`), and the mesh models (`../mesh/models/lit.ts`):
 * a building type ↔ its atlas frame names. This module is deliberately a LEAF —
 * it imports nothing from the mesh or the barrel, so `index.ts` can derive the
 * building-type set from `MESH_MODELS` without an import cycle.
 */

// ---------------------------------------------------------------------------
// Mill animation frames
// ---------------------------------------------------------------------------

/** Number of windmill-sail rotation frames (covers a 90° sweep; 4-fold sym). */
export const MILL_FRAME_COUNT = 8;

/** Frame name for mill sail rotation step `i` (0 → the base `bld/mill`). */
export function millFrameName(i: number): string {
  return i === 0 ? "bld/mill" : `bld/mill@${i}`;
}

// ---------------------------------------------------------------------------
// Dusk-lit window-glow variants
// ---------------------------------------------------------------------------

/**
 * Frame name for a building's DUSK-LIT variant (windows lamplit). The renderer
 * selects `bld/<type>@lit` by night factor, exactly like the mill's rotated
 * `@N` frames — render-only, deterministic. `@`-suffixed, so it's excluded from
 * BUILDING_SPRITE_TYPES (it's a frame of an existing type, not a new type).
 */
export function buildingLitFrameName(type: string): string {
  return `bld/${type}@lit`;
}

/** Building types that have a lit-window dusk variant (see `../mesh/models/lit.ts`). */
export const LIT_BUILDING_TYPES: readonly string[] = ["house", "bakery", "smith", "healer"];
